### ISSUE TITLE
Add ReaR logo to ReaR section on drlm.org About

### ISSUE THREAD

**Issue by schlomo** [brainupdaters/drlm#10]
On http://drlm.org/about/ you write about ReaR. Please feel free to also use our logo there. Logos can be found on https://github.com/rear/rear.github.com/tree/master/images/logos and may be used anywhere in relation to the Relax and Recover Open Source project.

**Comment by proura** [comment]
Done! Rear logo is already in the "About DRLM" section ( http://drlm.org/about/ ). You can take a look to see if everything is ok.

**Comment by schlomo** [comment]
Nice, thanks.
