### ISSUE TITLE
Update package URLs from upstream and add repo install for debian and ubuntu clients

### ISSUE THREAD

**Issue by didacog** [brainupdaters/drlm#114]
###### Quick response time is not guaranteed with free support, if you are using DRLM in a production environment and enterprise grade level support services are required, please see: http://www.brainupdaters.net/en/drlm-services.

Please fill in the following items before submitting a new issue:

##### Issue details:

* Issue type: **Feature Request**
* Impact: **Low**
* How often it happens: N/A
* Brief description of the issue: Since Ubuntu 18.04LTS (bionic) and Debian 10 (Buster), ReaR package is in distribution repositories, it should be integrated in installclient workflow.
Also an update to the upstream ReaR package URL's in default.conf is needed to install latest patched versions if needed on new OS versions.

**Comment by proura** [comment]
Hi @didacog,

@NefixEstrada and I are doing the testing with rear 2.5 version in our local default.conf. Inside Release 2.3.0 branch, when done, will do testing to check which version is compatible for each distribution and also to modify the dependencies, then will be applied to master and develop branches. 

In the case of Ubuntu 18.04 the ReaR version included in their repositories are ReaR 2.3 and there is an important issue for us solved in the 2.4 version :

> In the DRLM specific function drlm_import_runtime_config() solve problem with some variables loading config from DRLM (rear/rear issue #1794

and in the case of Debian 10 will be released in mid-2019 with ReaR 2.4. I have statarted to working on it and I do not know if we will have enough time to include in this release if not in the next.

**Comment by didacog** [comment]
@proura 

I was thinking in set REPO_URLS for the other distros (CentOS, RedHat, SLES,...) to control rear versions to install on them, without being forced to use too old versions of repos for rear.

**Comment by db260179** [comment]
Hi guys, this would be good to get the rear versions to the newer version. As i've just successfully installed your latest git version on debian 9, but faced an issue with the current tagged version of rear 2.2 - seems to stop the backup process from working - the CLI_KERNEL is empty due to some sort of mounting issue further down the line in the version of rear 2.2?

Updating to 2.5.0 of rear fixes this issue - have set a pull request for debian 9, but maybe someone can test this on debian 10 or ubuntu?

**Comment by proura** [comment]
Hi @db260179, in the coming days we will release DRLM 2.3.0 and as you can see here: https://github.com/brainupdaters/drlm/blob/2e885ff5163ef498760fa245cb7fa589258a9f17/usr/share/drlm/conf/default.conf#L308 where are updating all distros than have passed the tests to ReaR 2.5. Also we are testing on Debian 10 and updating ReaR packages.

Thank you!!!

**Comment by db260179** [comment]
Hi @proura Thanks for the update, must of missed that branch. I've closed my pull request as it has the same adjustments.

Just a side note, if u guys are interested in docker version, i have built this in docker and runs? let me know i can do a pull request?

**Comment by proura** [comment]
I do not have too much knowledge about docker, but @didacog is and expert of it and he maybe can take a look to your proposal. 

Thank you again @db260179 !!

**Comment by didacog** [comment]
Hi @db260179,
We better switch to issue #63 to talk about docker, to keep each issue for its own purpose. ;)

**Comment by proura** [comment]
@didacog Instclient workflow has been modified and standardized. Now Instclient installs ReaR package specified in default.conf file _for all distos_, but if you want to install from repositories you can use "-r/--repo" parameter. You can also continue using the parameter "-U/--url_rear" if you want use a diferent ReaR package.

I have tested in Debian[8-9-10], Centos[6-7] and Ubuntu [16-18] and works ok!

**Comment by didacog** [comment]
great news!! so we have the 2.3.0 release almost ready...
