### ISSUE TITLE
Listbakcup in pretty mode fails

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#120]
##### Issue details:

* Issue type: **Bug**
* Impact: **Low**
* How often it happens: **Always**
* Brief description of the issue: In listbackup workflow with pretty option enabled appears and extra line between each backup.
* Work-around, if any: this only happen when there are backups in the database without size and duration.

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): 2.3.0

**Comment by NefixEstrada** [comment]
#122 closes this
