### ISSUE TITLE
SSL local client generation failing due to incorrect install-functions.sh

### ISSUE THREAD

**Issue by db260179** [brainupdaters/drlm#125]
###### Quick response time is not guaranteed with free support, if you are using DRLM in a production environment and enterprise grade level support services are required, please see: http://www.brainupdaters.net/en/drlm-services.

Please fill in the following items before submitting a new issue:

##### Issue details:

* Issue type (**Bug** / **Question** / **Feature Request** / **Others?**):
Bug
* Impact (**Low** / **High** / **Critical** / **Urgent**):
High
* How often it happens (**Always** / **Eventually**):
Always
* Brief description of the issue:
The /usr/share/drlm/lib/install-functions.sh in the function send_ssl_cert () { is incorrect and missing a ${SUDO} and line spacing is breaking the whole function causing permission issues

My commit https://github.com/db260179/drlm/commit/ade1bb512f43ee51096871b983206c427843b69c
Will fix this issue

* Work-around, if any:
https://github.com/db260179/drlm/commit/ade1bb512f43ee51096871b983206c427843b69c
##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): 2.3.1 and below
* OS version (cat /etc/drlm/os.conf or lsb_release -a): All
* DRLM configuration files output: 
  * cat /etc/drlm/local.conf
  * cat /etc/drlm/clients/**client_name**.cfg

* DRLM error reporting configuration output (if applicable):
  * more /etc/drlm/alerts/*.cfg
  
* Output of: 
  * drlm listclient -c **client_name**
  * drlm listnetwork -A
  
##### DRLM Client information:

* ReaR version (/usr/sbin/rear -V):2.5.0
* OS version (cat /etc/rear/os.conf or lsb_release -a):
* ReaR configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Hardware platform (uname -i):
  * In case of i386/i686 or x86_64 platforms, BIOS or UEFI?

**Comment by didacog** [comment]
After the merge of PR #124  related to issue #63 this issue is solved, so can be closed.

Thanks @db260179 !!!

Regards,
Didac
