### ISSUE TITLE
wget package is a dependency in DRLM server?

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#127]
##### Issue details:

* Issue type: Bug/Question
* Impact: High
* How often it happens: Always
* Brief description of the issue:  wget is a dependency for DRLM?

```
root@deb10srv:~# dpkg -i drlm_2.3.1_all.deb 
Selecting previously unselected package drlm.
(Reading database ... 53006 files and directories currently installed.)
Preparing to unpack drlm_2.3.1_all.deb ...
Unpacking drlm (2.3.1) ...
dpkg: dependency problems prevent configuration of drlm:
 drlm depends on wget; however:
  Package wget is not installed.

dpkg: error processing package drlm (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 drlm
```
* Work-around, if any: remove dependency of wget from DRLM package. Wget is a dependency for ReaR clients.

##### DRLM Server information:

* DRLM version: Disaster Recovery Linux Manager 2.3.1
* OS version: Debian GNU/Linux 10 (buster)

**Comment by didacog** [comment]
we do not depend on it, and we always can use curl, so we can avoid this dependency in package files.
