### ISSUE TITLE
make clean leave drlm-api binary in place

### ISSUE THREAD

**Issue by didacog** [brainupdaters/drlm#130]
###### Quick response time is not guaranteed with free support, if you are using DRLM in a production environment and enterprise grade level support services are required, please see: http://www.brainupdaters.net/en/drlm-services.

Please fill in the following items before submitting a new issue:

##### Issue details:

* Issue type: Bug
* Impact: Low
* How often it happens : Always
* Brief description of the issue:
After creation of drlm package in any OS distro the drlm-api binary is not cleaned up upon make clean execution. 
* Work-around, if any: 
rm -f usr/sbin/drlm-api
This removal must be added to the clean section of Makefile and maybe also the resulting rpm/deb package should also be removed or moved outside the local git repo to complete clean it.

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): from 2.3.0

**Comment by proura** [comment]
Hi @didacog ,

the binary "drlm-api" is by default in the repo, but when make rpm/deb is execute is builded again and it makes it apper in changes not staged for commit. 

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   usr/sbin/drlm-api

```

If we put in make clean will appear as deleted.

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    ../usr/sbin/drlm-api
```

Maybe the solution will be delete "drlm-api" binary from the repo and then also add to make clean.

**Comment by didacog** [comment]
Hi @proura,

Yes, as we are building it, will be better to remove from it from the repo and clean it up with make clean.

**Comment by Peyoz** [comment]
This probably caused a regression, I uploaded a fix on PR #142

**Comment by Peyoz** [comment]
This caused a major regression, as now you absolutely need go installed to compile drlm-api and create the deb/rpm package.
I spotted it as I needed to build a new drlm server from hotfix 2.3.2.
Solution to this is trivial, as we can:
- Provide the binary, but remove the compile from make rpm/deb  target
- Remove the binary from the branch, but then we need to upgrade requirements with go (which is not readily available from package manager for most of the supported platform)

Thoughts?

**Comment by didacog** [comment]
Hi @Peyoz,

Well ..., IMHO this is a build requirement, not a package dependency. The build is completely documented for each supported distro. 

I don't see any issue on that, as we provide the source and how to build the packages.  

https://github.com/brainupdaters/drlm-docs/blob/master/docs/source/Install.rst#get-drlm
https://github.com/brainupdaters/drlm-docs/blob/master/docs/source/Install.rst#get-drlm-1
https://github.com/brainupdaters/drlm-docs/blob/master/docs/source/Install.rst#get-drlm-2
https://github.com/brainupdaters/drlm-docs/blob/master/docs/source/Install.rst#get-drlm-3
https://github.com/brainupdaters/drlm-docs/blob/master/docs/source/Install.rst#get-drlm-4
https://github.com/brainupdaters/drlm-docs/blob/master/docs/source/Install.rst#get-drlm-5

We provide built and tested packages with subscription or support plans, and as the package is already built, do not require any build dependency (golang).

Regards,
Didac

**Comment by Peyoz** [comment]
Hi @didacog ,
that's my fault, I was working on rhel without epel (which I'm not allowed to enable), and I probably missed the error on golang installation from yum.
Sorry about that,
Cheers

**Comment by didacog** [comment]
No problem!! ;)
