### ISSUE TITLE
delbackup issue

### ISSUE THREAD

**Issue by labbyjoel** [brainupdaters/drlm#134]
##### Issue details:

* Issue type (**Bug**):
* Impact ( **High** ):
* How often it happens (**Always**):
* Brief description of the issue:
impossible to use delbackup. I always get the "Backup is Enabled! Disable backup first" warning even the backup is disabled.

from the log : 
`2020-02-04 13:55:56 ERROR: WARNING: drlm:delbackup:ID(115.20200204132544):: Backup is Enabled! Disable backup first ....`

from the listbackup : 
`115.20200204132544   mail4           2020-02-04 13:25   disabled        0h.10m.50s      3.3G    `

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): Disaster Recovery Linux Manager 2.3.1-git / 2019-07-24
* OS version (cat /etc/drlm/os.conf or lsb_release -a): CentOS Linux release 7.6.1810 (Core)
* DRLM configuration files output: 
  * cat /etc/drlm/local.conf
NFS_SVC_NAME="nfs-server"
  * cat /etc/drlm/clients/**client_name**.cfg
```
`CLI_NAME=mail4
SRV_NET_IP=192.9.200.227

OUTPUT=PXE
OUTPUT_PREFIX=$OUTPUT
OUTPUT_PREFIX_PXE=$CLI_NAME/$OUTPUT
OUTPUT_URL=nfs://$SRV_NET_IP/var/lib/drlm/store/$CLI_NAME
BACKUP=NETFS
NETFS_PREFIX=BKP
BACKUP_URL=nfs://$SRV_NET_IP/var/lib/drlm/store/$CLI_NAME

SSH_ROOT_PASSWORD=drlm
BACKUP_PROG_EXCLUDE=( ${BACKUP_PROG_EXCLUDE[@]} '/home/mail/*' )
#
# Additional ReaR Configurations
#

# EXCLUDE_VG excludes the VGs from the client backup
# EXCLUDE_VG= ( 'Volume_Grup1' 'Volume_Grup2' )

# ONLY_INCLUDE_VG is the opposite of EXCLUDE_VG: only the specified VGs are going to be included to the client backup
# ONLY_INCLUDE_VG=( 'Volume_Grup1' 'Volume_Grup2' )

# EXCLUDE_MOUNTPOINTS excludes certain mountpoints from the client backup
# EXCLUDE_MOUNTPOINTS= ( '/Mount_Point1' 'Mount_Point2' )

# PRE_BACKUP_SCRIPT executes commands before running the backups. This could be used, for example, for stopping services
# PRE_BACKUP_SCRIPT=''

# POST_BACKUP_SCRIPT executes commands after running the backups. This could be used, for example, for starting services
# POST_BACKUP_SCRIPT=''


# SUSE 15 configuration example
### This configuration is used for running backups with a SUSE 15 client
# BACKUP_OPTIONS='nfsvers=4,nolock'
# REQUIRED_PROGS=( '${REQUIRED_PROGS[@]}' 'snapper' 'chattr' 'lsattr' )
# COPY_AS_IS=( '${COPY_AS_IS[@]}' '/usr/lib/snapper/installation-helper' '/etc/snapper/config-templates/default' )
# BACKUP_PROG_INCLUDE=( '/var/cache' '/var/lib/mailman' '/var/tmp' '/var/lib/pgsql' '/usr/local' '/opt /var/lib/libvirt/images' '/boot/grub2/i386-pc' '/var/opt' '/srv' '/boot/grub2/x86_64-efi' '/var/lib/mariadb' '/var/spool' '/var/lib/mysql' '/tmp /home' '/var/log' '/var/lib/named' '/var/lib/machines' )
# POST_RECOVERY_SCRIPT=( 'if snapper --no-dbus -r $TARGET_FS_ROOT get-config | grep -q "^QGROUP.*[0-9]/[0-9]" ; then snapper --no-dbus -r $TARGET_FS_ROOT set-config QGROUP= ; snapper --no-dbus -r $TARGET_FS_ROOT setup-quota && echo snapper setup-quota done || echo snapper setup-quota failed ; else echo snapper setup-quota not used ; fi' )
###

# Debian 10 configuration example
### This configuration is used for running backups with a Debian 10 client
# CLONE_USERS=( '${CLONE_USERS[@]}' '_rpc' )
###
`
```

  
* Output of: 
  * drlm listclient -c **client_name**
```
Id     Name            MacAddres       Ip               Client OS        ReaR Version     Network         Scheduled
115    mail4           109836ad3bd9    192.9.200.250    CentOS 7.3       2.5/2019-05-10   nWave           False    

```

**Comment by didacog** [comment]
Hello @labbyjoel,

did you run this before delbackup?
<pre>
# drlm bkpmgr --disable --id 115.20200204132544
     then
# drlm delbackup --id 115.20200204132544
</pre>

I've just tested on my CenOS drlm testing server and its working.

**Comment by didacog** [comment]
Ok, I've just seen your output with backup disabled....

please can you run the command in debug mode and update the log?

<pre>
# drlm -vD delbackup --id 115.20200204132544
</pre>

**Comment by didacog** [comment]
Looking at your DRLM version: Disaster Recovery Linux Manager **2.3.1-git / 2019-07-24**
Seems that you are using one from develop branch??
please use the latest release from master: Disaster Recovery Linux Manager **2.3.1-git / 2019-12-03**

That version is working on a CentOS DRLM server.

**Comment by didacog** [comment]
This is the correct stable package build process:
<pre>
~# yum -y install epel-release
~# yum -y install git rpm-build golang
~$ git clone https://github.com/brainupdaters/drlm
~$ cd drlm
~$ git checkout master 
~$ make rpm
</pre>

**Comment by labbyjoel** [comment]
Here is the log with the current version. 
I will reconfigure now with the master release and retry.. 

[drlm-nwave_couches-delbackup.20200204.155433.2886.log](https://github.com/brainupdaters/drlm/files/4154398/drlm-nwave_couches-delbackup.20200204.155433.2886.log)

**Comment by didacog** [comment]
@labbyjoel 

does this command works?
<pre>
# losetup -d loop115
</pre>

**Comment by didacog** [comment]
Also check if, somehow, you have any session using /var/lib/drlm/store/mail4 mountpoint.

If you can check the master branch is a good point anyway, develop branch is usually stable enough but sometimes, you know, is development and issues could happen.

**Comment by labbyjoel** [comment]
I've reinstall everything following your git instructions and I get this version : 

Disaster Recovery Linux Manager 2.3.1-git / 2019-07-03

The problem is still the same... 

```
drlm listbackup
              
Backup Id            Client Name     Backup Date        Backup Status   Duration        Backup Size
103.20200204163554   postgres        2020-02-04 16:35   disabled        0h.23m.24s      5.7G            
104.20200204170529   postgres-slave  2020-02-04 17:05   enabled         0h.2m.51s       1.2G            
101.20200204172810   scripts4        2020-02-04 17:28   enabled         0h.14m.34s      12G       
```
```
drlm delbackup -I 103.20200204163554
/dev/loop103: [64770]:30193386537 (/home/COUCHES/drlm/arch/postgres.103.20200204163554.dr)
ERROR: WARNING: drlm:delbackup:ID(103.20200204163554):: Backup is Enabled! Disable backup first .... 
Aborting due to an error, check /var/log/drlm/drlm-nwave_couches-delbackup.20200204.174736.5504.log for details
```
I've tried `losetup -d loop103` this command gaves no return.. 

a DF gaves me : 

`/dev/loop103                           54431016      5881276     47979036  11% /home/COUCHES/drlm/store/postgres`

FYI /var/lib/drlm is a symlink to /home/COUCHES/drlm

**Comment by didacog** [comment]
@labbyjoel 
Tomorrow I will try to reproduce your environment.
Somehow you disabled the backup and DRLM says that, but in fact the backup is mounted... so is strange that the disable command did not return any errors... 

I'll be back with my findings.

Regards,
Didac

**Comment by didacog** [comment]
Hi @labbyjoel,

I think the problem is with the symlink.
If you want to change default locations in DRLM, you mustang change:
<pre>
ARCHDIR=/home/COUCHES/drlm/arch
STORDIR=/home/COUCHES/drlm/store
</pre>
In /etc/drlm/local.conf

Try to umount the backups manualy using df output paths, losetup -d loopdevs and run delbackup.

After all backups removed, change these variables and try it  run/delbackups again.

Let me know if works please.

Regards,
Didac

**Comment by labbyjoel** [comment]
Hello! 

I've made those changes, and I can now delete the backups normally. 

The problem seems to be resolved removing the symlink. 

Thanks for your help !

**Comment by didacog** [comment]
Great to hear that!! 

Are you testing DRLM? did you come to this year FOSDEM talk?

**Comment by labbyjoel** [comment]
Yes I'm testing drlm in my company. I didn't plan to come on FOSDEM. I'm not a developper... just a CTO :-)

**Comment by didacog** [comment]
Ok, great! 

The talk was more about use cases, features, future, ... so if you have time take a look:
https://fosdem.org/2020/schedule/event/drlm/
there are the slides, videos and links to some asciinema demos.

Regards and thanks for testing DRLM!

**Comment by didacog** [comment]
I'm clossing this issue...
