### ISSUE TITLE
NFS_OPTS variable is not honored

### ISSUE THREAD

**Issue by bloodmoon85** [brainupdaters/drlm#138]
###### Quick response time is not guaranteed with free support, if you are using DRLM in a production environment and enterprise grade level support services are required, please see: http://www.brainupdaters.net/en/drlm-services.

Please fill in the following items before submitting a new issue:

##### Issue details:

* Issue type (Bug):
* Impact (**Low**):
* How often it happens (**Always**):
* Brief description of the issue:
NFS_OPTS variable is not honored because /usr/share/drlm/lib/nfs-functions.sh has static exports options.
Evidence is below
```
# grep -E "rw,|ro," nfs-functions.sh
    echo "$STORDIR/$CLI_NAME $CLI_NAME(rw,sync,no_root_squash,no_subtree_check)" | tee -a $NFS_FILE > /dev/null
  exportfs -vo ro,sync,no_root_squash,no_subtree_check ${CLI_NAME}:${STORDIR}/${CLI_NAME}
  #exportfs -vo rw,sync,no_root_squash,no_subtree_check ${CLI_NAME}:${STORDIR}/${CLI_NAME}
                echo "$STORDIR/$CLI_NAME $CLI_NAME(rw,sync,no_root_squash,no_subtree_check)" | tee -a $NFS_FILE > /dev/nulll
```
* Work-around, if any:
Add your parameters directly in /usr/share/drlm/lib/nfs-functions.sh

##### DRLM Server information:

* DRLM version : Disaster Recovery Linux Manager 2.3.1-git / 2019-07-24
* OS version : RHEL / CentOS 7
* DRLM configuration files output: 
  * cat /etc/drlm/local.conf
NFS_SVC_NAME="nfs-server"
BKP_CLI_PER=2
HISTBKPMAX=10
NFS_OPTS="rw,async,no_root_squash,no_subtree_check"

**Comment by bloodmoon85** [comment]
Hi,
I already patched my installation, let me know if I can provide you with the patch

**Comment by proura** [comment]
Hello @bloodmoon85,

Thank you very much in advance to use DRLM and give us feedback.

It is true, nowhere of the code apply the NFS_OPTS var. If you want to provide your patch you can fork DRLM in your own github account, apply your patch and then make a Pull Request to the brainupdaters Hotfix/2.3.2 branch.

For more detailed information in how to contribute you can read [CONTRIBUTING.rst](https://github.com/brainupdaters/drlm/blob/develop/CONTRIBUTING.rst) file in DRPM repository.

Thank you,

**Comment by bloodmoon85** [comment]
Hello!
i just made a PR for this issue, and it fixes the problem.
I had to think about a question: how can we approach a dynamic update of the exports file after an NFS_OPTS update?
A simple "trigger" on runbackup which checks the nfs export and recreate it if needed would suffice, what do you think about it?

**Comment by proura** [comment]
Hi @bloodmoon85!!
I have merged your PR into the hotfix branch. 
About the dynamic aproach of exports file, it is true that something must be done, maybe will be better to add in the /usr/sbin/drlm-stord service, and recreate the exports file every time drlm-stord service starts or restarts. There are some functions in nfs-functions.sh developed for that but never user, like generate_nfs_exports()... which option do you think would be best?

**Comment by bloodmoon85** [comment]
Hi @proura ,
thanks for pulling the request :) 
Talking about the enhancement, I saw that function at it looks good.
I can wrap it with some check and use it during the startup function in drlm-stord.
I will let you know in the next days,

Cheers :)

**Comment by bloodmoon85** [comment]
I messed with the comment and I closed the topic, I'm reopening as I have a PR for the enhancement :)
I took a different approach "unfortunately", but I think its a much more robust solution.
Let me know what do you think about :)

Cheers
