### ISSUE TITLE
Automatically generate client configuration file when a addclient is done.

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#18]
In order to facilitate the task of adding a client, will be created automatically the client configuration file with default values in /etc/drlm/client folder, thus avoiding having to be created manually.

**Comment by didacog** [comment]
Since version 2.0 is done on instclient workflow, but maybe will be better to do this at addclient time.

**Comment by krbu** [comment]
client configuration file with default values in /etc/drlm/client folder is now automatically created from the command **_"drlm addclient"_**
