### ISSUE TITLE
Problem installing client deps on RHEL 8.5 ppc64le - need to add arch control on rear deps packages in config.

### ISSUE THREAD

**Issue by janhoelscher** [brainupdaters/drlm#188]
##### Issue details:

* Issue type: Bug
* Impact: High
* How often it happens: Always
* Brief description of the issue: I want to use drlm instclient on a RHEL 8.5 Client on ppc64le Architecture it fails due to failed dependencies. Client has an error in dnf.log - `2022-03-16T10:23:42+0100 CRITICAL Error: Unable to find a match: syslinux`. I think the problem is, that there is no syslinux package for RHEL 8 on ppc64le. 

##### DRLM Server information:

* DRLM version: Disaster Recovery Linux Manager 2.4.1 / Git
* OS version: RHEL 8.5 on ppc64le 
  
##### Additonal Informations #####
The only package i can find, that has something to do with syslinux is syslinux-tftpboot.

```
Name         : syslinux-tftpboot
Version      : 6.04
Release      : 5.el8
Architecture : noarch
Size         : 462 k
Quelle       : syslinux-6.04-5.el8.src.rpm
Repository   : rhel-8-for-ppc64le-baseos-rpms
Summary      : SYSLINUX modules in /tftpboot, available for network booting
URL          : http://syslinux.zytor.com/wiki/index.php/The_Syslinux_Project
Lizenz       : GPLv2+
Description  : All the SYSLINUX/PXELINUX modules directly available for network
             : booting in the /tftpboot directory.
```
There are maybe some other bugs with ppc64le, but i think we should fix this one first.

**Comment by didacog** [comment]
Hello @janhoelscher,

Please try to put this line in /etc/drlm/local.conf:
REAR_DEP_REDHAT8="attr genisoimage libusal mtools **syslinux-tftpboot** nfs-utils wget bc net-tools rsync psmisc"

and try it again.

last time we tested RHEL7 & 8 or SLES12 & 15 for PPC64LE clients we had no issues, but we know that some packages could change. in that case we will add control  for ARCH in install  client deps.

Kind  regards,
Didac

**Comment by janhoelscher** [comment]
Hey @didacog, 

i can confirm that client install works with your small fix. Thanks for your help so far!

I now wanted to take a backup with sample `client_PXE` config. It seems there is are some problems to. Should i open a new issue? 

Kind Reg. 
Jan

**Comment by didacog** [comment]
Perfect! thanks for testing it @janhoelscher. We must add control on arch deps from now on seeing these package differences...

Yes please, open a new issue so we can track each problem and close them properly when finished.
