### ISSUE TITLE
Addclient on-line mode.

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#19]
The addclient command requires 4 parameters to be executed correctly: Client hostname, Client MAC, Clinet IP and Clinet Lan ID. (Ex: drlm addclient -c clientHost1 -M 00-40-77-DB-45-98 -i 15.75.80.13 -n vlan12)

This can be cumbersome, but it is the only way to do this if the client is not connected. But if  if the client is online and accessible this can be simplified getting all the information required connecting on it and just will be necessary to have the IP address. (Ex: drlm addclient -i 190.168.2.50 ).

this improvement will be developed to facilitate the use of AddClient command and DRLM management.

**Comment by didacog** [comment]
Well I'm ready to merge this...

       	new file:   ../client/add/default/079_check_collected_info.sh
       	modified:   ../client/add/default/059_check_workflow_params.sh
       	modified:   addclient-workflow.sh
       	modified:   dbdrv/sqlite3-driver.sh
       	modified:   help-functions.sh
       	modified:   network-functions.sh

**Comment by didacog** [comment]
Merged https://github.com/brainupdaters/drlm/commit/6b09773f218cc003779ab6ce912edfc828848eb7

**Comment by didacog** [comment]
Now it's possible to add a client to DRLM just providing IP/CIDR of the client. In case of any other parameters cannot be collected, can be provided manually.

Example:
<pre>
# drlm -vD addclient -i 192.168.56.203/24

The following information has been collected over network:

Name            MacAddres       Ip              Network
reardeb8        080027bfa7bc    192.168.56.203  hostonly

Confirm? [y/N]:

If wrong/none information collected, set it manually.
</pre>

Kind regards,

**Comment by didacog** [comment]
After some testing, is working as expected. i will close this issue.
