### ISSUE TITLE
This is less of an issue and more of a question

### ISSUE THREAD

**Issue by chumunga** [brainupdaters/drlm#197]
Is there a complete documentation some where? There is no mention of how to configure backup, do i configure the client /etc/rear/local.conf

or do i configure the backup from the server (DRLM) /etc/drlm/client/client_name.conf? and if so, how do even change the backup location?

###### Quick response time is not guaranteed with free support, if you are using DRLM in a production environment and enterprise grade level support services are required, please see: http://www.brainupdaters.net/en/drlm-services.

Please fill in the following items before submitting a new issue:

##### Issue details:

* Issue type (**Bug** / **Question** / **Feature Request** / **Others?**):
* Impact (**Low** / **High** / **Critical** / **Urgent**):
* How often it happens (**Always** / **Eventually**):
* Brief description of the issue:
* Work-around, if any:

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V):
* OS version (cat /etc/drlm/os.conf or lsb_release -a):
* DRLM configuration files output: 
  * cat /etc/drlm/local.conf
  * cat /etc/drlm/clients/**client_name**.cfg

* DRLM error reporting configuration output (if applicable):
  * more /etc/drlm/alerts/*.cfg
  
* Output of: 
  * drlm listclient -c **client_name**
  * drlm listnetwork -A
  
##### DRLM Client information:

* ReaR version (/usr/sbin/rear -V):
* OS version (cat /etc/rear/os.conf or lsb_release -a):
* ReaR configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Hardware platform (uname -i):
  * In case of i386/i686 or x86_64 platforms, BIOS or UEFI?

**Comment by proura** [comment]
Hi @chumunga,

- Is there a complete documentation some where? 

https://www.drlm.org

- There is no mention of how to configure backup, do i configure the client /etc/rear/local.conf or do i configure the backup from the server (DRLM) /etc/drlm/client/client_name.conf? 

The client config is automatically generated when a client is added to drlm server. This configuration is stored at /etc/drlm/client/client_name.conf and generates by default a rsync backup with an iso rescue image. The backup files are stored at /var/lib/drlm of DRLM server. You can also have multiple configurations per client, like  /etc/drlm/client/client_name.conf.d/config_name.cfg, and then run this configurations specifying it at runbackup command (ex. drlm runbackup -c client_name -C config_name)

-  and if so, how do even change the backup location?

DRLM clients (ReaR) backups are stored by default in "/var/lib/drlm/arch" of DRLM server root. You can change it at /etc/drlm/local.conf  variables 

```
# DRLM STORAGE LOCATIONS #
STORDIR=$VAR_DIR/store
ARCHDIR=$VAR_DIR/arch
```

You can find more costumizable  vars at /usr/share/drlm/conf/default.conf

Regards,

**Comment by chumunga** [comment]
Thank you,

for STOREDIR & ARCHDIR will this accept UNC paths //someserver/folder

Also, is there a way to reset or regenerate local.conf  I definitely botched mine.

**Comment by proura** [comment]
Hi @chumunga,

* **for STOREDIR & ARCHDIR will this accept UNC paths //someserver/folder**
The way to store backups in a remote site is mounting the someserver/folder in the DRLM server filesystem and then make that STOREDIR & ARCHDIR point there.

* **Also, is there a way to reset or regenerate local.conf I definitely botched mine.**
Yes, the way is running "drlm instclient -c client_name" this will reinstall all client packages and reset configurations. If you don't want to reintall packages you can run "drlm instclient -c client_name -C" an only configurations will be done. (https://drlm-docs.readthedocs.io/en/latest/client_opers.html#install-client)

* **My /var/lib/drlm/arch is empty**
Maybe you haven't done a successful runbackup yet?

* **And finally, i tried using the link on from the homepage to go to the google forum and received error 503 is that still a thing?**
True! we'll take a look, there's a problem accessing to the public group. Thank you for warning!
