### ISSUE TITLE
Change default DRLM STORAGE LOCATIONS in default.conf file

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#20]
To go keeping with the FSH is necessary to make the following changes: 

The next variables:
################ ---- DRLM STORAGE LOCATIONS
STORDIR=/DRLM/STORE
ARCHDIR=/DRLM/ARCH
DEPDIR=/DRLM/deps

must be replaced by:

################ ---- DRLM STORAGE LOCATIONS
STORDIR=$VAR_DIR/store
ARCHDIR=$VAR_DIR/arch
DEPDIR=$VAR_DIR/deps

**Comment by proura** [comment]
changes have been applied in the default.conf file.

**Comment by proura** [comment]
Mistakenly has been left the directory in CAPS. We have to change again.

**Comment by didacog** [comment]
Now applied on commit 49a6e32467350e4fc09957ee6acd203516871e42

**Comment by didacog** [comment]
for me no regressions after some tests... can be closed
