### ISSUE TITLE
Generating /etc/drlm/cert files...

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#21]
The drlm.crt and drlm.key files have to be generated for each installation of DRLM server in order to improve the security.

Command:
openssl req -newkey rsa:2048 -nodes -keyout /etc/drlm/cert/drlm.key -x509 -days 365 -subj "/C=ES/ST=CAT/L=GI/O=SA/CN=www.drlm.org" -out /etc/drlm/cert/drlm.crt

**Comment by didacog** [comment]
Tested on debian 7 and 8 and centos 6 and 7.

Al cert files are generated upon install. 

This issue can be closed.
