### ISSUE TITLE
curl 403 error from DRLM rescue

### ISSUE THREAD

**Issue by prontok** [brainupdaters/drlm#211]
Hello,
I tried to restore the operating system with PXE mode, but i have an error to restore

![Снимок экрана от 2023-05-25 14-43-54](https://github.com/brainupdaters/drlm/assets/90829636/845723cd-9465-48d8-a4d7-e9162eb628e1)

DRLM v2.4.10 (It works on Debian11)

P.S. Client registration and backup creation completes successfully and without problems

Key tokens of DRLM server and linux client are the same

Please help.

**Comment by didacog** [comment]
Hello,

Can you show the listclient output for the client? and the config file content/path you are using?

Thanks!
Didac
