### ISSUE TITLE
# Check if older versions than 2.4.12

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#237]
* Issue type: **Bug**
* Impact: **High**
* How often it happens: Updating DRLM from master to develop version
* Brief description of the issue:

This line that check drlm version generates a bad drlm_version value and do not update existing clients configs, which causes existing configurations to not work. 

https://github.com/brainupdaters/drlm/blob/a64b550742eb8b9eab48f2f866aecf144c45a409/packaging/debian/preinst#L32

```
root@drlmsrv:~# drlm_ver="$(awk 'BEGIN { FS="=" } /VERSION=/ { print $$2 }' /usr/sbin/drlm) | awk -F. '{printf("%02d%02d%02d\n", $1, $2, $3)}'"
root@drlmsrv:~# echo $drlm_ver 
2.4.12 | awk -F. '{printf(%02d%02d%02dn, , , )}'
```

On the other hand do not see where the configuration is updated in the rpm packages.

* Work-around, if any:

Add DRLM_BKP_SEC_PROT=no in all client configurations with RSYNC protocol or reinstall all clients.

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): from 2.4.11 to 2.4.12 (develop)
* OS version: Debian 1X, Rocky X
  
##### DRLM Client information:

* ReaR version (/usr/sbin/rear -V): Relax-and-Recover 2.7 / 2022-07-13
* OS version (cat /etc/rear/os.conf or lsb_release -a): Debian 12

**Comment by proura** [comment]
After testing I see that the configuration is still not applied to old clients on a DRLM Debian 12 server

**Comment by didacog** [comment]
Solved in last merged PR
