### ISSUE TITLE
Bakcup ID should be changed.

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#25]
ID backup is composed by Date and time in hh:mm:ss format. (ex.: 20160219123012)
May occur with parallel backups functionality that two backups ends up at the same second and cause an error in the database.

**Comment by gdha** [comment]
why don't you append the PID?

**Comment by proura** [comment]
Yes! Is a good idea!

**Comment by didacog** [comment]
Finally I've decided to append client ID to backup ID. I needed to solve this issue while rewriting new runbackup methods using qemu-img. Now should prevent errors with parallel backups.

**Comment by didacog** [comment]
Now the backup ID will be: $(date +"$CLI_ID.%Y%m%d%H%M%S")

example:  200.20160510154134

**Comment by didacog** [comment]
working as expected for me.. waiting to close until @proura and @krbu  finish their testings

**Comment by didacog** [comment]
All tests OK, closing
