### ISSUE TITLE
Add isolinux package for Debian 8

### ISSUE THREAD

**Issue by krbu** [brainupdaters/drlm#34]
With Debian 8 the isolinux.bin is not part of the syslinux package anymore.
Instead you need to explicitly install the isolinux package.  To avoid error on runbackup using debian 8 package isolinux must be installed.

**Comment by didacog** [comment]
This was solved by https://github.com/brainupdaters/drlm/commit/5ac76dcc035f4dc5fbebd66e72769065263fb0fc

I will close this issue.
