### ISSUE TITLE
New DRLM backup job scheduler 

### ISSUE THREAD

**Issue by didacog** [brainupdaters/drlm#35]
The new DRLM release (2.1.0) will have it's own backup job scheduler. This will result in some new workflows:

- addjob (Add jobs to DRLM)
- deljob (Delete jobs from DRLM)
- listjob (List defined jobs in DRLM)
- sched (Run scheduled backups in DRLM)

To schedule a job, at least a start date and DRLM client name will be defined.

Also an end date and job repetition will be defined as needed, but not as a required options. 

example of how a job will be defined:

$ drlm addjob -c client1 -s "2016-12-28 22:00" -r "1week"

In this example a backup for DRLM client "client1" will be scheduled every week at 22:00h on Wednesday starting on 28 december without end date.

The datetime formats could be any of the supported by linux command  'date' and repetition format also those supported by command 'date'. eg: 1day, 2week, 1month, 1year.

When I will finish all tests and the development of those new workflows I will update this issue with the final version. The DRLM documentation will be updated also to reflect these new feature.

We hope that DRLM users will see this new feature as useful as us ;)

Regards,

**Comment by didacog** [comment]
I have all the code ready for merge:

       	modified:   Makefile
       	new file:   etc/cron.d/drlm
       	modified:   packaging/debian/postinst
       	modified:   packaging/rpm/drlm.spec
       	modified:   usr/sbin/drlm
       	new file:   usr/share/drlm/backup/run/default/029_pid_control.sh
       	new file:   usr/share/drlm/backup/run/default/309_pid_control_rm.sh
       	new file:   usr/share/drlm/conf/DB/drlm_sqlite_schema.sql
       	modified:   usr/share/drlm/conf/default.conf
       	new file:   usr/share/drlm/job/add/default/059_check_workflow_params.sh
       	new file:   usr/share/drlm/job/add/default/209_register_job_to_db.sh
       	new file:   usr/share/drlm/job/del/default/059_check_workflow_params.sh
       	new file:   usr/share/drlm/job/del/default/159_delete_job_from_db.sh
       	new file:   usr/share/drlm/job/list/default/059_list_registered_jobs.sh
       	new file:   usr/share/drlm/job/sched/default/109_enable_disable_sched.sh
       	new file:   usr/share/drlm/job/sched/default/209_run_sched_backups.sh
       	new file:   usr/share/drlm/lib/addjob-workflow.sh
       	modified:   usr/share/drlm/lib/client-functions.sh
       	modified:   usr/share/drlm/lib/dbdrv/sqlite3-driver.sh
       	new file:   usr/share/drlm/lib/deljob-workflow.sh
       	modified:   usr/share/drlm/lib/help-functions.sh
       	new file:   usr/share/drlm/lib/job-functions.sh
       	new file:   usr/share/drlm/lib/listjob-workflow.sh
       	new file:   usr/share/drlm/lib/sched-workflow.sh
       	deleted:    var/lib/drlm/drlm.sqlite

I need to test it before merge.

Kind regards,

**Comment by didacog** [comment]
After several tests I solved some minor issues and now is merged on develop branch:

      	modified:   Makefile
       	modified:   packaging/debian/rules
       	modified:   usr/share/drlm/job/add/default/059_check_workflow_params.sh
       	modified:   usr/share/drlm/job/sched/default/209_run_sched_backups.sh
       	modified:   usr/share/drlm/lib/deljob-workflow.sh
       	modified:   usr/share/drlm/lib/job-functions.sh
       	modified:   usr/share/drlm/lib/listjob-workflow.sh

Reagads,

**Comment by didacog** [comment]
merged https://github.com/brainupdaters/drlm/commit/c606716810b4967f45d0b7c402c009d44bf0e166

**Comment by didacog** [comment]
I will update DRLM documentation, but in the meantime here there is some information on how to use it:

Add new Job:
<pre>
drlm addjob -c reardeb8 -s 2017-01-03T22:50 -e 2017-01-04T01:00 -r 10min
</pre>

Example date formats (no white-spaces allowed):

**-s / --start_date:**  %Y-%m-%dT%H:%M
**-e / --end_date:**  %Y-%m-%dT%H:%M
**-r / --repeat:** 1min(s) / 1hour(s) / 1day(s) / 1week(s) / 1month(s) / 1year(s)


Delete all jobs for a client:
<pre>
drlm deljob -c reardeb8
</pre>

List all Jobs:
<pre>
drlm listjob -A

Id    Client            End Date          Last Date         Next Date         Repeat
24    reardeb8          2017-01-04T01:00  2017-01-03T23:30  2017-01-03T23:40  10min
25    reardeb8          2017-01-04T01:00                    2017-01-03T23:50  15mins
</pre>

Delete a jobs by ID:
<pre>
drlm deljob -J 24
</pre>

**Comment by didacog** [comment]
We had an issue on handling enabled/disabled status of job scheduler. I solved it with this commit: https://github.com/brainupdaters/drlm/commit/51489cd09f5929835b2fae7a7c0062cdb580c12b

Kind regards,

**Comment by didacog** [comment]
Updated man mages with commit: https://github.com/brainupdaters/drlm/commit/a3a770ad1c26e1d2a0e09eee8f6afd044a2452c7

**Comment by didacog** [comment]
With this commit: https://github.com/brainupdaters/drlm/commit/7514b1b32ef413b681b9a7a2a198f79719ed56a9 was solved a problem with infinite loop on one-shot planned jobs.
Now this jobs without repetition (one-shot) are deleted from DB as they never will be used after it's execution.

Regards,

**Comment by didacog** [comment]
There was a bug on listjob by client, now solved with this commit: https://github.com/brainupdaters/drlm/commit/68fd1707cbd2b79999e8d6d4dfabc47cc4842efb

Regards,

**Comment by didacog** [comment]
Solved RPM build problem with this commit: https://github.com/brainupdaters/drlm/commit/b045ec779ef59eb4686819d35b885425aba93dd0

Regards,

**Comment by jonicks** [comment]
Nice and useful feature! Tested it with single jobs and repetitive ones and works really well.

**Comment by didacog** [comment]
Thanks @jonicks for testing it! with your comments and my tests, I can close this issue right now.

Can be re-opened any time if needed.
