### ISSUE TITLE
TFTP Problem (DRLM 2.0.0)

### ISSUE THREAD

**Issue by uxtuahgp** [brainupdaters/drlm#36]
On RedHat 7.1 
Trying to boot after drlm runbackup
Getting IP from DHCP, but get
PXE-E32 TFTP open timeout

**Comment by didacog** [comment]
Hi @uxtuahgp,

Regarding your issue, did you follow the documentation to configure TFTP service?

http://docs.drlm.org/en/latest/Install.html#centos-7-red-hat-7

Can you provide the TFTP service configuration?

Is SElinux or iptables enabled in your server?


Thanks for using DRLM!
Kind regards,

**Comment by uxtuahgp** [comment]
Good day, Didac.

Thanks for your support.

Of course i tried to follow the documentation.

[root@vr2-testnix-01 ~]# cat /etc/xinetd.d/tftp
# default: off
# description: The tftp server serves files using the trivial file transfer \
#       protocol.  The tftp protocol is often used to boot diskless \
#       workstations, download configuration files to network-aware printers, \
#       and to start the installation process for some operating systems.
service tftp
{
        socket_type             = dgram
        protocol                = udp
        wait                    = yes
        user                    = root
        server                  = /usr/sbin/in.tftpd
        server_args             = -s /var/lib/drlm/store
        disable                 = no
        per_source              = 11
        cps                     = 100 2
        flags                   = IPv4
        log_type                = FILE /var/log/tftp.log
}

[root@vr2-testnix-01 ~]# cat /etc/dhcp/dhcpd.conf
#
# DRLM DHCP Server Configuration file.
#

ddns-update-style none;
ddns-updates off;

deny declines;

default-lease-time 86400;
max-lease-time 604800;
allow booting;
allow bootp;

## ==========================================
# In initial DHCP DISCOVER packet, PXE client sets option 93 to its arch.
#    0000 == IA x86 PC (BIOS boot)
#    0006 == x86 EFI boot
#    0007 == x64 EFI boot
## ==========================================

option arch code 93 = unsigned integer 16;

if option arch = 00:00 {
  filename "boot/grub/i386-pc/core.0";
} elsif  option arch = 00:06 {
  filename "boot/grub/i386-efi/core.efi";
} elsif  option arch = 00:07 {
  filename "boot/grub/x86_64-efi/core.efi";
}


subnet 192.168.201.0 netmask 255.255.255.0 {
   option subnet-mask 255.255.255.0;
   option broadcast-address 192.168.201.255;
   option routers 192.168.201.1;
   next-server 192.168.201.1;
}
group {
# group header keept for possible future needs

   host vr2-testnix-02 {
      hardware ethernet 00:15:5d:7c:46:05;
      fixed-address 192.168.201.2;
   }
}



The server and client - are Hyper-V machines gen 1.
To use PXE boot we added Legacy Network Adapter to the Client machine configuration.

During PXE boot  i can see adapter obtains IP from DHCP, trying TFTP download, but...


On the DRLM server i can see:

[root@vr2-testnix-01 ~]# tcpdump -i eth1 port 69
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth1, link-type EN10MB (Ethernet), capture size 65535 bytes
13:07:55.669768 IP vr2-testnix-02.ah-esp-encap > 192.168.201.1.tftp:  41 RRQ "boot/grub/i386-pc/core.0" octet tsize 0
13:07:57.673987 IP vr2-testnix-02.acp-port > 192.168.201.1.tftp:  41 RRQ "boot/grub/i386-pc/core.0" octet tsize 0
13:08:01.683534 IP vr2-testnix-02.msync > 192.168.201.1.tftp:  41 RRQ "boot/grub/i386-pc/core.0" octet tsize 0
13:08:07.670408 IP vr2-testnix-02.gxs-data-port > 192.168.201.1.tftp:  41 RRQ "boot/grub/i386-pc/core.0" octet tsize 0
13:08:15.634581 IP vr2-testnix-02.vrtl-vmf-sa > 192.168.201.1.tftp:  41 RRQ "boot/grub/i386-pc/core.0" octet tsize 0
13:08:25.585774 IP vr2-testnix-02.newlixengine > 192.168.201.1.tftp:  46 RRQ "boot/grub/i386-pc/core.0" octet blksize 1456
13:09:01.607146 IP vr2-testnix-02.newlixconfig > 192.168.201.1.tftp:  46 RRQ "boot/grub/i386-pc/core.0" octet blksize 1456
13:10:13.614371 IP vr2-testnix-02.tsrmagt > 192.168.201.1.tftp:  46 RRQ "boot/grub/i386-pc/core.0" octet blksize 1456
13:12:01.597676 IP vr2-testnix-02.tpcsrvr > 192.168.201.1.tftp:  46 RRQ "boot/grub/i386-pc/core.0" octet blksize 1456
13:14:25.557161 IP vr2-testnix-02.idware-router > 192.168.201.1.tftp:  46 RRQ "boot/grub/i386-pc/core.0" octet blksize 1456


So, it seems i did something wrong.


>Среда, 11 января 2017, 14:34 +03:00 от Didac Oliveira <notifications@github.com>:
>
>Hi  @uxtuahgp ,
>Regarding your issue, did you follow the documentation to configure TFTP service?
>http://docs.drlm.org/en/latest/Install.html#centos-7-red-hat-7
>Can you provide the TFTP service configuration?
>Is SElinux or iptables enabled in your server?
>Thanks for using DRLM!
>Kind regards,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by didacog** [comment]
Hi @uxtuahgp,

DHCP and TFTP seems well configured. 

Starting with easy things... 

How many network adapters have the  vr2-testnix-02? In case of more than one, can you disable all except the Legacy one for PXE boot? And try it again?

Some virtualization environments have this kind of problems with PXE when have more than one net adapter attached.

On the other hand, if this is not the problem:

Please set tftp server in verbose mode (-s /var/lib/drlm/store -vvv), test it again an provide the log outputs and tcpdump also, but with (-n) option to avoid dns resolution.

These days I'm very busy with FOSDEM'17 Devroom preparation and closing the new DRLM release (2.1.0) , in addition to the day to day job itself. 
I don't know if It's urgent or you are just testing DRLM, but I cannot guarantee a fast response for the log analysis. Anyhow, when I can, I will take a look to help with your issue.

Kind regards,

**Comment by uxtuahgp** [comment]
Hi Didac!

I have just one Legacy Adapter. Should i try to disable the second virtual adapter? At the time of PXE boot VM don't know nothing about it.
I've set -vvv for tftp, but log file is empty after xinetd restart and PXE boot trial.

It seems, xinetd can't start tftp, but i'm relatively newbie in Linux and don't know exactly how to diagnose it.

Yes, i'm just testing DRLM for now.
It's not urgent.
Thanks for your work anyway!


>Четверг, 12 января 2017, 1:14 +03:00 от Didac Oliveira <notifications@github.com>:
>
>Hi  @uxtuahgp ,
>DHCP and TFTP seems well configured.
>Starting with easy things...
>How many network adapters have the  vr2-testnix-02? In case of more than one, can you disable all except the Legacy one for PXE boot? And try it again?
>Some virtualization environments have this kind of problems with PXE when have more than one net adapter attached.
>On the other hand, if this is not the problem:
>Please set tftp server in verbose mode (-s /var/lib/drlm/store -vvv), test it again an provide the log outputs and tcpdump also, but with (-n) option to avoid dns resolution.
>These days I'm very busy with FOSDEM'17 Devroom preparation and closing the new DRLM release (2.1.0) , in addition to the day to day job itself.
>I don't know if It's urgent or you are just testing DRLM, but I cannot guarantee a fast response for the log analysis. Anyhow, when I can, I will take a look to help with your issue.
>Kind regards,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by uxtuahgp** [comment]
Good day again.

I'm so sorry, but i'm dumb.
I've just found the root problem: firewalld is enabled by default in RHEL.


But now i have another issue:

I can see boot menu, choosing "System recovery using DRLM..." 
And get an errors: File not found, you need to load the kernel first




>Четверг, 12 января 2017, 1:14 +03:00 от Didac Oliveira <notifications@github.com>:
>
>Hi  @uxtuahgp ,
>DHCP and TFTP seems well configured.
>Starting with easy things...
>How many network adapters have the  vr2-testnix-02? In case of more than one, can you disable all except the Legacy one for PXE boot? And try it again?
>Some virtualization environments have this kind of problems with PXE when have more than one net adapter attached.
>On the other hand, if this is not the problem:
>Please set tftp server in verbose mode (-s /var/lib/drlm/store -vvv), test it again an provide the log outputs and tcpdump also, but with (-n) option to avoid dns resolution.
>These days I'm very busy with FOSDEM'17 Devroom preparation and closing the new DRLM release (2.1.0) , in addition to the day to day job itself.
>I don't know if It's urgent or you are just testing DRLM, but I cannot guarantee a fast response for the log analysis. Anyhow, when I can, I will take a look to help with your issue.
>Kind regards,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by uxtuahgp** [comment]
One more step: found that after delclient client cfg file appear to be  removed.
created cfg
launched runbackup
fail again
it seems not enough 52M of space, given by DRLM server  for rear PXE images:

vr2-testnix-02:/var/log/rear # grep space rear-vr2-testnix-02.log
cp: failed to close '/tmp/rear.5V2x8f6PQc6p4j3/outputfs/PXE/vr2-testnix-02.initrd.cgz': No space left on device
cp: failed to close '/tmp/rear.5V2x8f6PQc6p4j3/outputfs/PXE/VERSION': No space left on device
cp: failed to close '/tmp/rear.5V2x8f6PQc6p4j3/outputfs/PXE/README': No space left on device
cp: failed to close '/tmp/rear.5V2x8f6PQc6p4j3/outputfs/PXE/rear.log': No space left on device






>Четверг, 12 января 2017, 1:14 +03:00 от Didac Oliveira <notifications@github.com>:
>
>Hi  @uxtuahgp ,
>DHCP and TFTP seems well configured.
>Starting with easy things...
>How many network adapters have the  vr2-testnix-02? In case of more than one, can you disable all except the Legacy one for PXE boot? And try it again?
>Some virtualization environments have this kind of problems with PXE when have more than one net adapter attached.
>On the other hand, if this is not the problem:
>Please set tftp server in verbose mode (-s /var/lib/drlm/store -vvv), test it again an provide the log outputs and tcpdump also, but with (-n) option to avoid dns resolution.
>These days I'm very busy with FOSDEM'17 Devroom preparation and closing the new DRLM release (2.1.0) , in addition to the day to day job itself.
>I don't know if It's urgent or you are just testing DRLM, but I cannot guarantee a fast response for the log analysis. Anyhow, when I can, I will take a look to help with your issue.
>Kind regards,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by didacog** [comment]
Hi @uxtuahgp,

Well seems TFTP problem was solved disabling iptables, true?

For the new problem, can you provide the following?

- logfile of: drlm -vD runbackup -c vr2-testnix-02 

- logfile of rear: rear-vr2-testnix-02.log

- output from vr2-testnix-02: curl -k https://192.168.201.1/clients/vr2-testnix-02

- output from drlm: ssh -ttt drlm@vr2-testnix-02 sudo rear dump REST_OPTS=-k SERVER=192.168.201.1 ID=vr2-testnix-02

I suspect could be some problem on the HTTP configuration that for RedHat is a little bit tricky to configure yet: http://docs.drlm.org/en/latest/Install.html#id19

Kind regards,

**Comment by uxtuahgp** [comment]
Hi Didac!

I'll provide this information later
but what i discovered:
Used size of /boot is 52MB, but the system uses compressed kernel
When the runbackup works, it calculates DR_IMG_SIZE_MB as 52MB, but actually /var/lib/rear/output/vr2-testnix-02.initrd.cgz weights about 150MB.

Is it helpful?


>Пятница, 13 января 2017, 11:34 +03:00 от Didac Oliveira <notifications@github.com>:
>
>Hi  @uxtuahgp ,
>Well seems TFTP problem was solved disabling iptables, true?
>For the new problem, can you provide the following?
>* 
>logfile of: drlm -vD runbackup -c vr2-testnix-02
>* 
>logfile of rear: rear-vr2-testnix-02.log
>* 
>output from vr2-testnix-02: curl -k  https://192.168.201.1/clients/vr2-testnix-02
>* 
>output from drlm: ssh -ttt drlm@vr2-testnix-02 sudo rear dump REST_OPTS=-k SERVER=192.168.201.1 ID=vr2-testnix-02
>I suspect could be some problem on the HTTP configuration that for RedHat is a little bit tricky to configure yet:  http://docs.drlm.org/en/latest/Install.html#id19
>Kind regards,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by didacog** [comment]
Yes, could be a problem gathering client mountpoint info. 
Also can you provide the client configuration /etc/drlm/clients/vr2-testnix-02.cfg and the output from mount -l of the client?

regards,

**Comment by ismaelchasco** [comment]
Hi, 
I have had the same problem. It was because I have named the client in DRLM different from the real host. And the file /var/lib/drlm/store/boot/cfg/MAC creates well but the /var/lib/drlm/store/DRLMhost/PXE/host.kernel gives the host real name. Is the reason that it doesn,t found.
If you delete the client and create again, becareful with /var/lib/drlm/store/boot/cfg/MAC file because it doesn't changes.
I don't know if I explained well XD

**Comment by uxtuahgp** [comment]
Hi Didac!

Have you received the e-mail with attached requested logs?


>Пятница, 13 января 2017, 12:12 +03:00 от Didac Oliveira <notifications@github.com>:
>
>Yes, could be a problem gathering client mountpoint info.
>Also can you provide the client configuration /etc/drlm/clients/vr2-testnix-02.cfg and the output from mount -l of the client?
>regards,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by didacog** [comment]
Hi @uxtuahgp,

No, I didn't receive anything by e-mail, just your previous comment.

Regards,

**Comment by uxtuahgp** [comment]
How could i correctly upload zip archive with logs for you?
There was attachment in my previous e-mail too.


>Понедельник, 16 января 2017, 22:53 +03:00 от Didac Oliveira <notifications@github.com>:
>
>Hi  @uxtuahgp ,
>No, I didn't receive anything by e-mail, just your previous comment.
>Regards,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by didacog** [comment]
Hi
Is a large zip file? I didn't received any attachment o even e-mail.

Maybe you can share them as text using a Gist (https://gist.github.com/) If you have problems to send them by e-mail? 

Also, can you give me your e-mail address? just to test if we can receive and send e-mails from our accounts between us and there is no problem.

I've checked spam folder also and nothing.

Regards,

**Comment by uxtuahgp** [comment]
alex_dubrovsky at mail.ru


>Вторник, 17 января 2017, 13:10 +03:00 от Didac Oliveira <notifications@github.com>:
>
>Hi
>Is a large zip file? I didn't received any attachment o even e-mail.
>Maybe you can share them as text using a Gist ( https://gist.github.com/ ) If you have problems to send them by e-mail?
>Also, can you give me your e-mail address? just to test if we can receive and send e-mails from our accounts between us and there is no problem.
>I've checked spam folder also and nothing.
>Regards,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by didacog** [comment]
Hi @uxtuahgp 

Hi had some time to check your logs and I've opened a new issue #41.

As your problem with TFTP has been solved while disabling firewalld on DRLM server, I will close this issue and use #41 to discuss on this new problem

You can re-open this issue if you think it is required.
