### ISSUE TITLE
Problemas con la instalación del cliente

### ISSUE THREAD

**Issue by ismaelchasco** [brainupdaters/drlm#38]
Al hacer la instalación desatendida para un cliente debian8. Falla porque no instala todas las dependencias necesarias.

Comando del servidor DRLM: 
`drlm -vD instclient -c Cliente1 -U http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_8.0/amd64/rear_2.00_amd64.deb`

Error:
```
2017-01-15 11:16:41 ####################################################
2017-01-15 11:16:41 # Install Dependencies and ReaR                    #
2017-01-15 11:16:41 ####################################################
Connection to cliente1 closed.
2017-01-15 11:16:42 Installing dependendies and ReaR
Connection to cliente1 closed.
2017-01-15 11:16:56 Dependencies has been installed
Connection to cliente1 closed.
2017-01-15 11:16:56 ERROR: Error installing ReaR, check logfile
=== Stack trace ===
Trace 0: /usr/sbin/drlm:251 main
Trace 1: /usr/share/drlm/lib/instclient-workflow.sh:120 WORKFLOW_instclient
Trace 2: /usr/share/drlm/lib/framework-functions.sh:85 SourceStage
Trace 3: /usr/share/drlm/lib/framework-functions.sh:40 Source
Trace 4: /usr/share/drlm/client/inst/default/359_install_client_soft.sh:24 source
Message: Error installing ReaR, check logfile
```

Solución:
Instalar en el cliente las siguientes dependencias: 
`xorriso iproute isolinux dosfstools binutils`

**Comment by proura** [comment]
Gracias @ismaelchasco, 

Estos días estamos un poco ocupados preparando una Devroom para el FOSDEM'17 y desarrollando la release 2.1.0, tan pronto como nos sea possible lo revisaremos.

**Comment by ismaelchasco** [comment]
Y otro problema que he encontrado, es que cuando se lanza el recover desde el cliente vía PXE, el grub lo carga bien, carga bien los kernels, pero cuando llega a ReaR pierde la IP. Si se lanza un dhclient interfaz, recupera la IP y funciona todo guay. Si no, no consigue el backup del server y no restaura nada y ya no inicia el sistema.
Igual todo lo que os comento lo tenéis solucionado en la 2.1.0. Pero justo me he puesto hoy un par de ratos a probar la herramienta y he tenido algún problemilla (que mas o menos he conseguido solucionar XD). Si necesitáis que replique alguno de los problemas me comentáis. Que la herramienta me mola.

**Comment by didacog** [comment]
Hola @ismaelchasco,

Prueba en poner USE_DHCLIENT=y en el fichero de configuración del cliente (/etc/rear/local.conf).
Esto debería configurar la IP de forma automática. 

Deberas ejecutar drlm runbackup de nuevo para aplicar el cambio en el initrd del rescue.

Saludos,

-------------
Hi @ismaelchasco,

Try to set USE_DHCLIENT=y in the client config file (/etc/rear/local.conf).
This should configure IP using DHCP. 

You should run drlm runbackup again to apply the change into the recovery image.

Regards,

**Comment by ismaelchasco** [comment]
Me sigue sin funcionar :S. Creo que es porque el comando dhclient lo ejecuta pero no con la interfaz... Si que aparece en el archivo de rear cuando se ejecuta por PXE pero no consigue IP. Cuando saque un rato intento revisar a ver si encuentro el porqué.
Grazie por la info!

**Comment by didacog** [comment]
Hola @ismaelchasco,

Por si te puede servir de ayuda, puedes probar esto también: https://github.com/rear/rear/pull/960#issuecomment-239448861
Por cierto, ¿estás tratando de restaurar en el mismo u otro servidor/VM?

Saludos,

---------------------------------
Hi @ismaelchasco,
Maybe this can help you: https://github.com/rear/rear/pull/960#issuecomment-239448861
By the way, are you trying to restore on the same or a different server/VM?

Regards,

**Comment by didacog** [comment]
Hi, rear dependencies have been updated, now should work. Debian 7 will automatically install rear 1.18. It's last version without xorriso package requirement.

See those new configuration settings:

############### ----- REAR DEB PACKAGE URL

URL_REAR_UBUNTU12_32="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_7.0/i386/rear_1.18_i386.deb"
URL_REAR_UBUNTU12_64="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_7.0/amd64/rear_1.18_amd.deb"
URL_REAR_UBUNTU14_32="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_14.04/i386/rear_1.18_i386.deb"
URL_REAR_UBUNTU14_64="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_14.04/amd64/rear_1.18_amd64.deb"
URL_REAR_UBUNTU16_32="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_16.04/i386/rear_2.00_i386.deb"
URL_REAR_UBUNTU16_64="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_16.04/amd64/rear_2.00_amd64.deb"
URL_REAR_DEBIAN6_32="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_7.0/i386/rear_1.18_i386.deb"
URL_REAR_DEBIAN6_64="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_7.0/amd64/rear_1.18_amd.deb"
URL_REAR_DEBIAN7_32="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_7.0/i386/rear_1.18_i386.deb"
URL_REAR_DEBIAN7_64="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_7.0/amd64/rear_1.18_amd64.deb"
URL_REAR_DEBIAN8_32="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_8.0/i386/rear_2.00_i386.deb"
URL_REAR_DEBIAN8_64="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_8.0/amd64/rear_2.00_amd64.deb"

############### ----- REAR DEPENDENCIES

REAR_DEP_REDHAT5="install mkisofs mingetty syslinux nfs-utils cifs-utils portmap wget curl parted"
REAR_DEP_REDHAT6="install mkisofs mingetty syslinux nfs-utils cifs-utils rpcbind wget curl parted"
REAR_DEP_REDHAT7="install mkisofs mingetty syslinux nfs-utils cifs-utils rpcbind wget curl parted"
REAR_DEP_DEBIAN6="syslinux ethtool genisoimage parted gawk attr sudo curl mingetty libgssglue1 libtirpc1 python python2.7 python2.7-minimal python-minimal mime-support portmap lsb-release file"
REAR_DEP_DEBIAN7="syslinux ethtool genisoimage parted gawk attr sudo curl mingetty libgssglue1 libtirpc1 python python2.7 python2.7-minimal python-minimal mime-support rpcbind lsb-release file nfs-common iputils-ping"
REAR_DEP_DEBIAN8="syslinux ethtool parted gawk attr sudo curl mingetty libgssglue1 libtirpc1 python python2.7 python2.7-minimal python-minimal mime-support rpcbind lsb-release file iproute binutils nfs-common dosfstools xorriso isolinux iputils-ping"
REAR_DEP_UBUNTU12="syslinux ethtool genisoimage parted gawk attr sudo curl mingetty libgssglue1 libtirpc1 python python2.7 python2.7-minimal python-minimal mime-support rpcbind lsb-release file iproute binutils nfs-common iputils-ping openssl"
REAR_DEP_UBUNTU14="syslinux ethtool genisoimage parted gawk attr sudo curl mingetty libgssglue1 libtirpc1 python python2.7 python2.7-minimal python-minimal mime-support rpcbind lsb-release file iproute binutils nfs-common iputils-ping openssl"
REAR_DEP_UBUNTU16="syslinux ethtool parted gawk attr sudo curl mingetty libgssglue1 libtirpc1 python python2.7 python2.7-minimal python-minimal mime-support rpcbind lsb-release file iproute binutils nfs-common iputils-ping dosfstools xorriso isolinux"

**Comment by jonicks** [comment]
Tested the last update and unattended installation in Debian / Ubuntu clients works as expected. No more dependencies issues :) @ismaelchasco

**Comment by didacog** [comment]
Good news! then I will close this issue.

Can be re-opened if needed.

Regards,
