### ISSUE TITLE
NEW Import & Export DR images between DRLM servers

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#39]
This enhancement will provide more agility to DRLM admin when manipulate DR images.

- **exportdr** (export DR image from DRLM server)
- **importdr** (import DR image to an existent client)

example:
exportdr -I 195.20170110154134
importdr -c client1 -I 195.20170110154134

We also have in mind to develop the following workflow to facilitate the movement of massive data, but  maybe in the next release.

Move client data and all their backups.
- **exportcli** (export Client data from DRLM server)
- **importcli** (import Client data to DRLM server)

Move network data and all client data and their backups.
- **exportnet** (export Network data from DRLM server)
- **importnet** (import Network data to DRLM server)

When I will finish all tests and the development of those new workflows I will update this issue with the final version. The DRLM documentation will be updated also to reflect these new feature.

We hope that DRLM users will see this new feature as useful as us.

Regards,

**Comment by proura** [comment]
Actually drlm is albe to export and import backups. Two workflows have been created, expbackup and impbackup, to accomplish this tasks.

### - **expbackup** (export DR image from DRLM server)
Expbackup makes a copy of the selected dr file to the selected destination.

The **drlm expbackup** has some requiered options

> **-I** backup_id, **--id** backup_id   (Select backup to export)
> **-f** filename, **--file** filename  (Filename where the backup will be exported)


### - **impbackup** (import DR image to an existent client)
Impbackup generates a new backup_id for the specified file to import and copies to arch folder of DRLM server with the new id, mount the new DR in the store/client folder and change the filenames of the files in the store/client/pxe to fit to the new client's configuration and insert the new backup to the database. Import a new backup will ignore the feature of HISTBKPMAX (Max numbers of backups to keep in filesystem) until runbackup is executed again. It is important to remember that the hostname of the imported client must be manully changed to the hostname in the DRLM database.

The **drlm impbackup** has some requiered options:

>  **-c** client_name, **--client** client_name (Select client to import backup)
>  **-f** filename, **--file** filename (Filename from the backup will be imported)

examples:
```
drlm expbackup -I 195.20170110154134 -f /home/drlm/export_client195.dr
drlm impbackup -c client82 -f /home/drlm/export_client195.dr
```

**Comment by jonicks** [comment]
Tested the new feature and could easily export a backup from one server to import it to another one and from there recover a client. Awesome new feature @proura

**Comment by proura** [comment]
Thanks @jonicks for testing it! with your comments and all the other tests, I can close this issue right now.

Can be re-opened any time if needed.
