### ISSUE TITLE
Problem gathering DR image size on clients using BTRFS with snapshots enabled/mounted 

### ISSUE THREAD

**Issue by didacog** [brainupdaters/drlm#41]
This issue is being opened after the logs provided by @uxtuahgp in issue #36 showed us this problem/bug.

**Comment by didacog** [comment]
Hi @uxtuahgp,

Can you provide the client OS & version? is a SUSE system?

Regards,

**Comment by didacog** [comment]
HI @uxtuahgp,

Assuming your drlm client is SUSE and has +16GB disk, the problem could be with snapper, see this: https://www.suse.com/documentation/sles-12/book_sle_admin/data/sec_snapper_setup.html

Snapper on SUSE Linux Enterprise Server is set up to serve as an undo and recovery tool for system changes. By default, the root partition (/) of SUSE Linux Enterprise Server is formatted with Btrfs. **Taking snapshots is automatically enabled if the root partition (/) is big enough (approximately more than 16 GB)**. Taking snapshots on partitions other than / is not enabled by default.

With this scenario a snapshot is mounted on (/):
<pre>
/dev/mapper/system-root on / type btrfs (rw,relatime,space_cache,subvolid=259,subvol=/@/.snapshots/1/snapshot)
</pre>  
instead of the root subvolulme (/@) :
<pre>
/dev/mapper/system-root on / type btrfs (rw,relatime,space_cache,subvolid=259,subvol=/@)
</pre>  

My last commit in develop should solve your problem. We had a similar issue few weeks ago, but we couldn't reproduce it until I received your logs and I have had some time to check them.
I encourage you to build the RPM from the develop branch: http://docs.drlm.org/en/latest/Install.html#id12, test it, and update this issue with the results.I have no time to test it properly right now. 

Hope this helps to solve it.

Regards,

**Comment by uxtuahgp** [comment]
Hi, Didac!

It's SUSE Linux Enterprize for SAP applications ver. 12 SP2  


>Среда, 18 января 2017, 23:55 +03:00 от Didac Oliveira <notifications@github.com>:
>
>Hi  @uxtuahgp ,
>Can you provide the client OS & version? is a SUSE system?
>Regards,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by uxtuahgp** [comment]
Hi Didac.

After I installed new DRLM I tried to make drlm runbackup
It's completed successfully.
I can see boot image and the tar.gz backup file in TFTP dir.

But when i tried to boot from PXE it hung on "Welcome to GRUB!"



>Четверг, 19 января 2017, 4:26 +03:00 от Didac Oliveira <notifications@github.com>:
>
>HI  @uxtuahgp ,
>Assuming your drlm client is SUSE and has +16GB disk, the problem could be with snapper, see this:  https://www.suse.com/documentation/sles-12/book_sle_admin/data/sec_snapper_setup.html
>Snapper on SUSE Linux Enterprise Server is set up to serve as an undo and recovery tool for system changes. By default, the root partition (/) of SUSE Linux Enterprise Server is formatted with Btrfs.  Taking snapshots is automatically enabled if the root partition (/) is big enough (approximately more than 16 GB) . Taking snapshots on partitions other than / is not enabled by default.
>With this scenario a snapshot is mounted on (/):
>/dev/mapper/system-root on / type btrfs (rw,relatime,space_cache,subvolid=259,subvol=/@/.snapshots/1/snapshot)
>instead of the root subvolulme (/@) :
>/dev/mapper/system-root on / type btrfs (rw,relatime,space_cache,subvolid=259,subvol=/@)
>My last commit in develop should solve your problem. We had a similar issue few weeks ago, but we couldn't reproduce it until I received your logs and I have had some time to check them.
>I encourage you to build the RPM from the develop branch:  http://docs.drlm.org/en/latest/Install.html#id12 , test it, and update this issue with the results.I have no time to test it properly right now.
>Hope this helps to solve it.
>Regards,
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by uxtuahgp** [comment]
Oops!
One more try, and boot menu appeared.
But when i tried to recover 
rear recover SERVER=192.168.201.1 REST_OPTS=-k ID=vr2-testnix-02
it's failed 

[rear-vr2-testnix-02.zip](https://github.com/brainupdaters/drlm/files/717064/rear-vr2-testnix-02.zip)

**Comment by didacog** [comment]
Hi @uxtuahgp,

Ok, I'm glad to know that the fix worked fine.

This issue regarding BTRFS problem is now fixed, I will close this issue and reopen a new one with the correct topic  once I can check the logs updated.

Is ok for you?

**Comment by uxtuahgp** [comment]
Hi, Didac.

It's ok.
Unfortunately, i didn't make snapshot of client VM, so i urged to re-install Linux, cause it's broken.


>Пятница, 20 января 2017, 14:03 +03:00 от Didac Oliveira <notifications@github.com>:
>
>Hi  @uxtuahgp ,
>Ok, I'm glad to know that the fix worked fine.
>This issue regarding BTRFS problem is now fixed, I will close this issue and reopen a new one with the correct topic  once I can check the logs updated.
>Is ok for you?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

**Comment by didacog** [comment]
Well, just to confirm one thing.

Did you configured network in de rescue, before rear recover?

try this: dhclient <NIC>

and then rear recover ....

I'm sorry but I cannot guarantee fast response, if you are using DRLM on production and need guaranteed response times,... please check the DRLM Support services available here: http://www.brainupdaters.net/en/drlm-services/

**Comment by didacog** [comment]
Hi @uxtuahgp,

I've just checked your logfile:

Your error:
<pre>
+++ chattr +C /mnt/local//@/var/lib/libvirt/images
/var/lib/rear/layout/diskrestore.sh: line 202: chattr: command not found
2017-01-19 15:36:13 An error occurred during layout recreation.
2017-01-19 15:44:52 User selected: 6) Abort Relax-and-Recover
2017-01-19 15:44:52 Error detected during restore.
2017-01-19 15:44:52 Restoring backup of /var/lib/rear/layout/disklayout.conf
2017-01-19 15:44:52 ERROR: There was an error restoring the system layout. See /var/log/rear/rear-vr2-testnix-02.log for details.
</pre>

You are using ReaR 1.18. Since its version 2.0 there was a fix to automatically include lsattr and chattr binaries in recovery image in case of there are required. See this commit: https://github.com/rear/rear/commit/725aea3e99df7c956ea2011cea852a79968a79c1

For SLES client configurations you should follow this example ReaR configuration: https://github.com/rear/rear/blob/6c31e79dc6a21b891ee644f3ffacd22761b698f9/usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf

<pre>
# On SLE12-SP1 and SP2 with default btrfs subvolumes what is mounted at '/' is a btrfs snapshot subvolume
# that is controlled by snapper so that snapper is needed in the recovery system.
# In SLE12-SP1 and SP2 some btrfs subvolume directories (/var/lib/pgsql /var/lib/libvirt/images /var/lib/mariadb)
# have the "no copy on write (C)" file attribute set so that chattr is required in the recovery system
# and accordingly also lsattr is useful to have in the recovery system (but not strictly required):
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" snapper chattr lsattr )
# Snapper setup by the recovery system uses /usr/lib/snapper/installation-helper
</pre>

In ReaR version you are using is a must.

Now your problem is that you do not have lsattr or chattr or snapper binaries in your rescue image. As you already have network in your booted recovery image, you can follow next steps:

1. Extract those binaries from /var/lib/drlm/store/vr2-testnix-02/BKP/backup.tar.gz

2. Copy them to recovery image's bin directory over the network.

3. Run "rear recover SERVER=192.168.201.1 REST_OPTS=-k ID=vr2-testnix-02" again. 

You should be able to recover the VM successfully.

Hope this helped.

I will close this issue because the error you are having now is not related to this issue topic and you tested the fix successfully. 

Can be re-opened if required.

Regards,
