### ISSUE TITLE
Support for drlm unattended installation (instclient) on Ubuntu

### ISSUE THREAD

**Issue by jonicks** [brainupdaters/drlm#43]
Hi,

I did some minor changes in order to make the instclient feature available on Ubuntu clients. I had to modify the following files:

- ## **default.conf** 

I added the **REAR DEB PACKAGES URL** section so rear can be installed without entering its download URL. Manual URL introduction still works. 

<pre>
############### ----- REAR DEB PACKAGE URL

URL_REAR_UBUNTU12_32="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_12.04/i386/rear_1.18_i386.deb"

URL_REAR_UBUNTU12_64="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_12.04/all/rear_1.17.2_all.deb"

URL_REAR_UBUNTU14_32="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_14.04/i386/rear_1.18_i386.deb"

URL_REAR_UBUNTU14_64="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_14.04/amd64/rear_1.18_amd64.deb"

URL_REAR_UBUNTU16_32="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_16.04/i386/rear_2.00_i386.deb"

URL_REAR_UBUNTU16_64="http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_16.04/amd64/rear_2.00_amd64.deb"
</pre>

Added the **REAR DEPENDENCIES** of these packages:
<pre>
REAR_DEP_UBUNTU12="syslinux ethtool genisoimage parted gawk attr sudo curl mingetty libgssglue1 libtirpc1 python python2.7 python2.7-minimal python-minimal mime-support rpcbind lsb-release file iproute binutils nfs-common iputils-ping openssl"
REAR_DEP_UBUNTU14="syslinux ethtool genisoimage parted gawk attr sudo curl mingetty libgssglue1 libtirpc1 python python2.7 python2.7-minimal python-minimal mime-support rpcbind lsb-release file iproute binutils nfs-common iputils-ping openssl"
REAR_DEP_UBUNTU16="syslinux ethtool genisoimage parted gawk attr sudo curl mingetty libgssglue1 libtirpc1 python python2.7 python2.7-minimal python-minimal mime-support rpcbind lsb-release file iproute binutils nfs-common iputils-ping dosfstools xorriso isolinux"
</pre>

Added the **REAR SERVICES** to initialize:

<pre>
REAR_SERVICES_UBUNTU12="portmap"
REAR_SERVICES_UBUNTU14="rpcbind"
REAR_SERVICES_UBUNTU16="rpcbind"
</pre>

- ## **install-functions.sh**

 I modified _function get_distro_ so it recognizes both Debian and Ubuntu distros.

<pre>
function get_distro () {
 if [ -f /etc/dpkg/origins/ubuntu ]; then echo Ubuntu;fi
 if [ -f /etc/debian_version ] && [ ! -f /etc/dpkg/origins/ubuntu ]; then echo Debian;fi
</pre>

Added instructions in _function get_release_ to get the release of the Ubuntu distro:
<pre> if [ -f /etc/dpkg/origins/ubuntu ]; then lsb_release -rs; fi</pre>

Modified function _install_dependencies_apt_ as follows:

<pre>
function install_dependencies_apt () {
 local USER=$1
 local CLI_NAME=$2
 local REAR_DEP_DEBIAN="$3"
 **local REAR_DEP_UBUNTU="$3"**
 local SUDO=$4
 **if [[ ${DISTRO} -eq "Debian" ]]; then**
 ssh -ttt ${USER}@${CLI_NAME} "( ${SUDO} apt-get -y install ${REAR_DEP_DEBIAN[@]} &> /dev/null)"
 **else
 ssh -ttt ${USER}@${CLI_NAME} "( ${SUDO} apt-get -y install ${REAR_DEP_UBUNTU[@]} &> /dev/null)"
 fi**
 
 if [ $? -eq 0 ]; then return 0; else return 1; fi
}
</pre>

Modified function _start_services_ to also start Ubuntu's required services:
<pre>
function start_services () {
 for service in ${SERVICES[@]}
 do
        ${SUDO} service $service start
    **if [[ ${DISTRO} == "Debian" ]] || [[ ${DISTRO} == "Ubuntu" ]]**
    then 
        ${SUDO} update-rc.d $service enable
        else
        ${SUDO} chkconfig $service on
        fi
 done
}
</pre>

- ## **109_create_user_on_client**
Added the following line between RELEASE and ARCH variables to get a shortened version of the Ubuntu release version number. 
<pre>
RELEASE=$(ssh_get_release $USER $CLI_NAME)
if [ $DISTRO == "Ubuntu" ]; then VERSION=$(echo $RELEASE|cut -c 1,2); else VERSION=$(echo $RELEASE|cut -c 1); fi
ARCH=$(get_arch $USER $CLI_NAME)
</pre>

- ## **359_install_client_soft.sh**

And now I was ready to add a dedicated Ubuntu case between Debian and Centos ones:

<pre>
Ubuntu)
    case ${VERSION} in
            1[2-6])
                        if check_apt ${USER} ${CLI_NAME} ${SUDO}
                         then
                            LogPrint "Installing dependencies and ReaR"
                            if [[ ${VERSION} == 12 ]]
                            then
                                if install_dependencies_apt  ${USER} ${CLI_NAME} "${REAR_DEP_UBUNTU12}" ${SUDO}; then Log "Dependencies have been installed"; else Error "Error installing dependencies, check logfile"; fi
                            fi   
                            if [[ ${VERSION} == 14 ]]
                            then
                                if install_dependencies_apt  ${USER} ${CLI_NAME} "${REAR_DEP_UBUNTU14}" ${SUDO}; then Log "Dependencies have been installed"; else Error "Error installing dependencies, check logfile"; fi
                            fi    
                            if [[ ${VERSION} == 16 ]]
                            then
                                   if install_dependencies_apt  ${USER} ${CLI_NAME} "${REAR_DEP_UBUNTU16}" ${SUDO}; then Log "Dependencies have been installed"; else Error "Error installing dependencies, check logfile"; fi
                            fi
                            
                            if [[ ${URL_REAR} != "" ]]; then                             
                                if ssh_install_rear_dpkg ${USER} ${CLI_NAME} ${URL_REAR} ${SUDO}; then Log "ReaR has been installed"; else Error "Error installing ReaR, check logfile"; fi
                            else
                                if [[ ${ARCH} == "x86_64" ]] && [[ ${VERSION} == 12 ]] ; then
                                    URL_REAR=${URL_REAR_UBUNTU12_64}
                                    if ssh_install_rear_dpkg ${USER} ${CLI_NAME} ${URL_REAR} ${SUDO}; then Log "ReaR has been installed"; else Error "Error installing ReaR, check logfile"; fi
                                fi
                                if [[ ${ARCH} == "i686" ]] && [[ ${VERSION} == 12 ]] ; then
                                    URL_REAR=${URL_REAR_UBUNTU12_32}
                                    if ssh_install_rear_dpkg ${USER} ${CLI_NAME} ${URL_REAR} ${SUDO}; then Log "ReaR has been installed"; else Error "Error installing ReaR, check logfile"; fi
                                fi
                                if [[ ${ARCH} == "x86_64" ]] && [[ ${VERSION} == 14 ]] ; then 
                                    URL_REAR=${URL_REAR_UBUNTU14_64}
                                    if ssh_install_rear_dpkg ${USER} ${CLI_NAME} ${URL_REAR} ${SUDO}; then Log "ReaR has been installed"; else Error "Error installing ReaR, check logfile"; fi
                                fi
                                if [[ ${ARCH} == "i686" ]] && [[ ${VERSION} == 14 ]] ; then
                                    URL_REAR=${URL_REAR_UBUNTU14_32}
                                    if ssh_install_rear_dpkg ${USER} ${CLI_NAME} ${URL_REAR} ${SUDO}; then Log "ReaR has been installed"; else Error "Error installing ReaR, check logfile"; fi
                                fi
                                
                                if [[ ${ARCH} == "x86_64" ]] && [[ ${VERSION} == 16 ]] ; then
                                    URL_REAR=${URL_REAR_UBUNTU16_64}
                                    if ssh_install_rear_dpkg ${USER} ${CLI_NAME} ${URL_REAR} ${SUDO}; then Log "ReaR has been installed"; else Error "Error installing ReaR, check logfile"; fi
                                fi
                                if [[ ${ARCH} == "i686" ]] && [[ ${VERSION} == 16 ]] ; then
                                    URL_REAR=${URL_REAR_UBUNTU16_32}
                                    if ssh_install_rear_dpkg ${USER} ${CLI_NAME} ${URL_REAR} ${SUDO}; then Log "ReaR has been installed"; else Error "Error installing ReaR, check logfile"; fi
                                fi
                            fi    
                            
                                
                        else
                            Error "apt-get problem, some dependencies are missing, check requisites on http://drlm-docs.readthedocs.org/en/latest/ClientConfig.html"
                        fi
                        
                        if [[ ${VERSION} == 12 ]]
                        then
                           if ssh_start_services ${USER} ${CLI_NAME} "${REAR_SERVICES_UBUNTU12}" ${DISTRO} ${SUDO}; then LogPrint "Services have been started succesfully"; else "ERROR starting services"; fi
                        fi
                        if [[ ${VERSION} == 14 ]]
                        then
                           if ssh_start_services ${USER} ${CLI_NAME} "${REAR_SERVICES_UBUNTU14}" ${DISTRO} ${SUDO}; then LogPrint "Services have been started succesfully"; else "ERROR starting services"; fi
                        fi
                        if [[ ${VERSION} == 16 ]]
                        then
                           if ssh_start_services ${USER} ${CLI_NAME} "${REAR_SERVICES_UBUNTU16}" ${DISTRO} ${SUDO}; then LogPrint "Services have been started succesfully"; else "ERROR starting services"; fi
                        fi
                        ;;
                *)
                        echo "Ubuntu version not identified or unsupported!"
                        ;;
    esac
    ;;
</pre>

Modifications were tested in LTS versions of Ubuntu, the ones still supported by Canonical.

**Comment by didacog** [comment]
Hi @jonicks,

Thanks for your contribution to DRLM! I will update develop branch with your changes if you tested them. Next time will be better to do a pull request ;)

Regards,

**Comment by jonicks** [comment]
I tested the modifications in all supported LTS Ubuntu versions. No crashes so far and everything seems to work as expected. Thank you!

**Comment by didacog** [comment]
Cool! merged! ;)

**Comment by jonicks** [comment]
Superb! Thanks!

**Comment by didacog** [comment]
@jonicks I've also improved a little bit the debian installation with your code! ;)

Many thanks!

**Comment by jonicks** [comment]
@didacog That sounds great!

**Comment by jonicks** [comment]
Much better error handling and screen output while in instclient process with the last two commits. Thank you @didacog

**Comment by didacog** [comment]
Ok, then I will close this issue.

Thanks @jonicks!

Can be re-opened if needed.
