### ISSUE TITLE
sudo commands does not work on OEL 5 11

### ISSUE THREAD

**Issue by sesantam** [brainupdaters/drlm#56]
###### Quick response time is not guaranteed with free support, if you are using DRLM in a production environment and enterprise grade level support services are required, please see: http://www.brainupdaters.net/en/drlm-services.

Please fill in the following items before submitting a new issue:

##### Issue details:

Hello!

I'm testing DRLM over OEL client platform and I see a sudo problem when executing "runbackup" on OEL 5.11.

I had to change "/usr/share/drlm/lib/backup-functions.sh" file by including full path for sudo commands in order to get it working.

I'm attaching three files zipped with this issue:

[DRLM_sudo_OEL_5_11.zip](https://github.com/brainupdaters/drlm/files/842105/DRLM_sudo_OEL_5_11.zip)

- Failed backup log for password prompt on sudo command: drlm-drlmsrv-runbackup.20170314.170133.4160.log
- Diff on shell script backup-functions.sh changes on sudo commands mount, vgs and stat: backup_functions.diff
- Successful backup log when changes applied: drlm-drlmsrv-runbackup.20170314.174127.7292.log

* Issue type (**Bug** / **Question** / **Feature Request** / **Others?**): Bug
* Impact (**Low** / **High** / **Critical** / **Urgent**): Low
* How often it happens (**Always** / **Eventually**): Always
* Brief description of the issue:  sudo does not work on OEL 5 11
* Work-around, if any: Add full path for "vgs", "mount" and "stat" commands on "backup-functions.sh" functions: get_fs_free_mb, get_fs_size_mb, get_client_used_mb

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): 

```
[root@drlmsrv ~]# drlm -V
Disaster Recovery Linux Manager 2.1.2-git / 2017-03-10
```

* OS version (cat /etc/drlm/os.conf or lsb_release -a):

```
[root@drlmsrv ~]# lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.6 (Santiago)
Release:        6.6
Codename:       Santiago
```

* DRLM configuration files output: 
  * cat /etc/drlm/local.conf

```
[root@drlmsrv ~]# cat /etc/drlm/local.conf
ONLY_INCLUDE_VG=( 'vg00' )
```

  * cat /etc/drlm/clients/**client_name**.cfg
```
[root@drlmsrv ~]# cat /etc/drlm/clients/oel-5-11.cfg
# This file has been generated by instclient , it can be modified at your convenience, see http://relax-and-recover.org/ for more information
CLI_NAME=oel-5-11
SRV_NET_IP=192.168.1.6

OUTPUT=PXE
OUTPUT_PREFIX=$OUTPUT
OUTPUT_PREFIX_PXE=oel-5-11/$OUTPUT
OUTPUT_URL=nfs://192.168.1.6/var/lib/drlm/store/oel-5-11
BACKUP=NETFS
NETFS_PREFIX=BKP
BACKUP_URL=nfs://192.168.1.6/var/lib/drlm/store/oel-5-11

SSH_ROOT_PASSWORD=drlm
[root@drlmsrv ~]#
```

* DRLM error reporting configuration output (if applicable):
  * more /etc/drlm/alerts/*.cfg
  
* Output of: 
  * drlm listclient -c **client_name**

```
[root@drlmsrv ~]#  drlm listclient -c oel-5-11

Id     Name            MacAddres       Ip              Client OS       Network
1      oel-5-11        005056010bc4    192.168.1.12                    vcloud
[root@drlmsrv ~]#
```

  * drlm listnetwork -A

```
[root@drlmsrv ~]# drlm listnetwork -A

Id     Ip              Mask            Gw              Broadcast       Server Ip       Name                               
1      192.168.1.0     255.255.255.0   192.168.1.1     192.168.1.255   192.168.1.6     vcloud
[root@drlmsrv ~]#
```

##### DRLM Client information:

* ReaR version (/usr/sbin/rear -V):

```
[root@OEL-5-11 ~]# /usr/sbin/rear -V
Relax-and-Recover 2.00 / Git
[root@OEL-5-11 ~]#
```
* OS version (cat /etc/rear/os.conf or lsb_release -a):

```
[root@OEL-5-11 ~]# lsb_release -a
LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: EnterpriseEnterpriseServer
Description:    Enterprise Linux Enterprise Linux Server release 5.11 (Carthage)
Release:        5.11
Codename:       Carthage
[root@OEL-5-11 ~]#
```

* ReaR configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):

```
[root@OEL-5-11 ~]# cat /etc/rear/local.conf
DRLM_MANAGED=y
[root@OEL-5-11 ~]#
```

* Hardware platform (uname -i):
  * In case of i386/i686 or x86_64 platforms, BIOS or UEFI?

```
[root@OEL-5-11 ~]# uname -i
x86_64
[root@OEL-5-11 ~]#
```
BIOS

Cheers.

Sergio

**Comment by krbu** [comment]
Hi sesantam,

Thanks for the testing, I'm working on it. I don't think to hardcode the full path is agood idea since can be diferent depending of the distro. It'll be fixed very soon on the next hotfix.

Thanks again.

**Comment by sesantam** [comment]
Hi krbu!

Thanks for the feedback!

See you

**Comment by krbu** [comment]
Hi @sesantam, it has been fixed as you commented.

**Comment by sesantam** [comment]
Hi!

Fixed :+1:  thanks

See you!
