### ISSUE TITLE
drlm runbackup hangs upon collecting data from client

### ISSUE THREAD

**Issue by bonevg** [brainupdaters/drlm#64]
###### Quick response time is not guaranteed with free support, if you are using DRLM in a production environment and enterprise grade level support services are required, please see: http://www.brainupdaters.net/en/drlm-services.

Please fill in the following items before submitting a new issue:

##### Issue details:

* Issue type **Bug**
* Impact **Low** - popped up upon testing functionality for 1st time
* How often it happens **Always**
* Brief description of the issue: **"runbackup" not working on RHEL 7**
* Work-around, if any: ** unable to debug e.g. no workround yet **

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): 
`Disaster Recovery Linux Manager 2.2.0 / Git`
* OS version (cat /etc/drlm/os.conf or lsb_release -a): 
`LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: LinuxMint
Description:    Linux Mint 18.3 Sylvia
Release:        18.3
Codename:       sylvia`

* DRLM configuration files output: 
  * cat /etc/drlm/local.conf
`DHCP_SVC_NAME="isc-dhcp-server"
NFS_SVC_NAME="nfs-kernel-server"`

  * cat /etc/drlm/clients/**client_name**.cfg
`
cat /etc/drlm/clients/test1.cfg
CLI_NAME=test1
SRV_NET_IP=192.168.56.1

OUTPUT=PXE
OUTPUT_PREFIX=$OUTPUT
OUTPUT_PREFIX_PXE=$CLI_NAME/$OUTPUT
OUTPUT_URL=nfs://$SRV_NET_IP/var/lib/drlm/store/$CLI_NAME
BACKUP=NETFS
NETFS_PREFIX=BKP
BACKUP_URL=nfs://$SRV_NET_IP/var/lib/drlm/store/$CLI_NAME

SSH_ROOT_PASSWORD=drlm
`
* DRLM error reporting configuration output (if applicable):
  * more /etc/drlm/alerts/*.cfg`
  
* Output of: 
* drlm listclient -c test1
`
Id     Name            MacAddres       Ip              Client OS       Network  
2      test1           0800273a704e    192.168.56.20                   test    
`   

  * drlm listnetwork -A
`Id     Ip              Mask            Gw              Broadcast       Server Ip       Name                                     
1      192.168.56.0    255.255.255.0   192.168.56.1    192.168.56.255  192.168.56.1    test   `       
##### DRLM Client information:

* ReaR version (/usr/sbin/rear -V):
`/usr/sbin/rear -V
Relax-and-Recover 2.00 / Git`

* OS version (cat /etc/rear/os.conf or lsb_release -a):
`/usr/sbin/rear -V
Relax-and-Recover 2.00 / Git
(Linux test1 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux)`
* ReaR configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
`
DRLM_MANAGED=y
`
* Hardware platform (uname -i):
`
x86_64
`
  * In case of i386/i686 or x86_64 platforms, BIOS or UEFI?
`BIOS`

 * Additional Info:
I can see the DRLM server logs into the client by SSH and starts the workflows, however it hangs.
More clarity in the log bellow (process interrupted via CTRL+C):
`
2018-02-12 16:12:44 Disaster Recovery Linux Manager 2.2.0 / Git
2018-02-12 16:12:44 Command line options: /usr/sbin/drlm runbackup -c test1
2018-02-12 16:12:44 Including /etc/drlm/local.conf
2018-02-12 16:12:44 Running runbackup workflow
2018-02-12 16:12:44 Running 'backup/run' stage
2018-02-12 16:12:44 Including backup/run/default/019_check_client_backup_reqs.sh
2018-02-12 16:12:44 ------------------------------------------------------------------
2018-02-12 16:12:44 drlm :
2018-02-12 16:12:44
2018-02-12 16:12:44  - Starting DR backup operations for Client: test1
2018-02-12 16:12:44
2018-02-12 16:12:44  - Start Date & Time:
2018-02-12 16:12:44 ------------------------------------------------------------------
2018-02-12 16:12:44 drlm:runbackup: Checking if client name: test1 is registered in DRLM database ...
2018-02-12 16:12:44 drlm:runbackup: Client test1 found!
2018-02-12 16:12:44 drlm:runbackup: Testing connectivity for test1 ... ( ICMP - SSH )
2018-02-12 16:12:44 drlm:runbackup: Client test1 SSH Server is online!
2018-02-12 16:12:44 Including backup/run/default/029_pid_control.sh
2018-02-12 16:12:44 drlm:runbackup:Running backup for client [ test1 ] with PID: 2889.
2018-02-12 16:12:44 Including backup/run/default/049_calc_dr_img_size.sh
2018-02-12 16:12:44 drlm:runbackup:REMOTE:getspace:DR:test1: Collecting DR Image space requirements...
Connection to test1 closed.^M
2018-02-12 16:21:01 ERROR: drlm:runbackup:REMOTE:getspace:DR:test1: Problem collecting remote space! aborting ...
=== Stack trace ===
Trace 0: /usr/sbin/drlm:254 main
Trace 1: /usr/share/drlm/lib/runbackup-workflow.sh:86 WORKFLOW_runbackup
Trace 2: /usr/share/drlm/lib/framework-functions.sh:85 SourceStage
Trace 3: /usr/share/drlm/lib/framework-functions.sh:40 Source
Trace 4: /usr/share/drlm/backup/run/default/049_calc_dr_img_size.sh:16 source
Message: drlm:runbackup:REMOTE:getspace:DR:test1: Problem collecting remote space! aborting ...
===================
2018-02-12 16:21:01 Running exit tasks.
`

**Comment by didacog** [comment]
Hello @bonevg,
Did you solved the problem? I see the issue opened and closed ...

Thanks for testing DRLM!

**Comment by bonevg** [comment]
Greetings,
I still might have missed something in the documentation, but I gave it a
try couple of times before I decided it is a bug.

The problem was the manual provisioning of the client. I was about to open
new issue when I have the time to re-test if that was real problem.
However.. the automatic provisioning of the client with drlm instclient
works perfect, (so perhaps some steps are missing in the manual
step-by-step provisioning).

=== Way to reproduce ====
Client OS RHEL -7.4 / DRLM server OS Linux Mint - Sonya
Ways to reproduce would be:
------
0) on drlm server:  add drlm network and drlm client
1)  manually do step-by-step installation of the client by following the
drlm.org documentation
2)  try to run drlm runbackup from the server

*Behaviour*: drlm login into client and start performing operations. Hangs
on:

// drlm server logs
ERROR: drlm:runbackup:REMOTE:getspace:DR:ussd1: Problem collecting remote
space! aborting ...
=== Stack trace ===
Trace 0: /usr/sbin/drlm:254 main
Trace 1: /usr/share/drlm/lib/runbackup-workflow.sh:86 WORKFLOW_runbackup
Trace 2: /usr/share/drlm/lib/framework-functions.sh:85 SourceStage
Trace 3: /usr/share/drlm/lib/framework-functions.sh:40 Source
Trace 4: /usr/share/drlm/backup/run/default/049_calc_dr_img_size.sh:16
source
Message: drlm:runbackup:REMOTE:getspace:DR:ussd1: Problem collecting remote
space! aborting ...
===================

Additional tests that I did is to login on the client and:    su - drlm.
All sudo commands described it the /etc/suduers.d/drlm are working properly.
E.g. sudo vgs; sudo mount; sudo rear

Didn't have time to borrow head into the shell scripts that are used for
deeper debugging.

If I am to find something, I will open a ticket to notify the community.

PS: I also noticed that automatic provisioning places its own
/etc/rear/local.conf, which I tried and used on manually provisioned client
system, but it still had the same issue. Just hanging on gathering disk
space info.

Best Regards,

**Comment by bonevg** [comment]
Now when I think of it - I don't remember doing the rpcbind and the nfs
services on the client side.
Will check again.

**Comment by didacog** [comment]
Ok, update the issue again when you fiished your tests. 
As you said, If you are working with manual install of clients, maybe something is missing on the client side. Is working with installcient provisioned clients?

**Comment by krbu** [comment]
Hi, can you show us the content of cat /etc/sudoers.d/drlm ?

**Comment by krbu** [comment]
I didn't test drlm in a LinuxMint, but the content should be: 

_Cmnd_Alias DRLM = /usr/sbin/rear, /bin/mount, /sbin/vgs, /usr/bin/stat
drlm    ALL=(root)      NOPASSWD: DRLM_

DRLM needs to execute some commands  as root, "stat " is used on some functions to get the free space. When "drlm instclient" is used to setup the client /etc/sudoers.d/drlm is populated with the required comands after checking the location of the comands. Since the location is changing depending of the distro we decided to not put the content of the file and allow drlm to do it.

**Comment by bonevg** [comment]
@ krbu
The /etc/suduers.d/drlm file works Ok. The syntax is also correct (visudo -c)
To be sure it was not the problem I've used a drlm sudoers file from an automated client installation.
PS: The Linux Mint in my tests is the server part. The drlm/rear client is RHEL 7.4.

**Comment by krbu** [comment]
Ok, can you attach the output of the next command executed by drlm user?

for line in $(df -h|awk '{print $6}'|grep -v Mounted); do sudo /usr/bin/stat $line; done

**Comment by krbu** [comment]
can you attach also the entire log?

**Comment by bonevg** [comment]
I just noticed that "stat" is executed via "sudo stat" by drlm user.
But In /etc/sudoers.d/drlm we only have definitions for "mount, vgs and rear". 
I have updated the /etc/sudoers.d/drlm file to include CmdAlias for stat and it works.

**Comment by krbu** [comment]
Ok, no worries, thanks for the testing anyway. You're right about the documentation, but since the comands on the sudo file may change depending of the distro we decided to doit automatically via "drlm instclient".
