### ISSUE TITLE
"${BACKUP_PROG_EXCLUDE[@]}" Ignored!!!

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#68]
##### Issue details:

* Issue type: ReaR Bug
* Impact: Urgent
* How often it happens: Always
* Brief description of the issue: the "${BACKUP_PROG_EXCLUDE[@]}" var in the /etd/drlm/clients/clientname.cfg is ignored on launch runbackup.
* Work-around, if any: 

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): Disaster Recovery Linux Manager 2.2.0-git / 2017-09-20
* OS version (cat /etc/drlm/os.conf or lsb_release -a): Red Hat Enterprise Linux Server release 7.4 (Maipo)
  
##### DRLM Client information:

* ReaR version (/usr/sbin/rear -V): Relax-and-Recover 2.2 / 2017-07-20
* OS version (cat /etc/rear/os.conf or lsb_release -a): Red Hat Enterprise Linux Server release 6.8 (Santiago)

**Comment by didacog** [comment]
Well, it is now solved in ReaR master branch and will be ready for ReaR 2.4.

I'm closing the issue. The next steps should be to include the next rear 2.4 version as DRLM default.
