### ISSUE TITLE
SSH Port is hardcoded in check_ssh_port() function

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#70]
* Issue type: Feature Request
* Impact: Low
* How often it happens: Always
* Brief description of the issue: If ssh server of DRLM client isn't configured by port 22 DRLM server don't reach to manage them
* Work-around, if any:  In order to check if ssh client is available over the network is used check_ssh_port() function.

function check_ssh_port ()
{
  local ip=$1
  return $(check_net_port $ip **22** &>/dev/null) 
}

Is necessary to change the hardcoded port number of this function by a configurable variable.

##### DRLM Server information:

* DRLM version: Disaster Recovery Linux Manager 2.2.0-git / 2017-09-20

 
##### DRLM Client information:

SSH server not in default port 22

**Comment by krbu** [comment]
New variable _SSH_PORT_ has been created on _default.conf_ file and has been added to _SSH_OPTS_ to allow user to choose the ssh port. 
function _check_ssh_port_ has been changed aswell to fix the hardcoded port 
_ssh-copi-id_ command has been modified on file _109_create_user_on_client.sh_ for the same reason

**Comment by proura** [comment]
I have tested and found that SSH_OPTS are always set to port 22 because read the variable SSH_PORT and assigns the value before reading the local.conf file.

**Comment by krbu** [comment]
Then if SSH_PORT is used on local.conf is mandatory to use SSH_OPTS also

**Comment by proura** [comment]
Ok! Pefect! Do it and remember to update the release notes also.

**Comment by proura** [comment]
@krbu I have merged the SSH Paramters in Default.conf file in order to close the Issue and move ToDoc.
