### ISSUE TITLE
SERVER, REST_OPTS and ID from ReaR client file /etc/rear/local.conf ignored on runbackup.

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#71]
* Issue type: Bug
* Impact: Low
* How often it happens: Always
* Brief description of the issue: Client doesn't reach the DRLM server for DNS problems and I decide to change the hostname SERVER var in /etc/rear/local.conf for the IP but the problems continues
* Work-around, if any:
In the run_mkbackup_ssh_remote fuction the runbackup command is called with some variables imposed by DRLM server, this causes that the variables defined in the client configuration file to be ignored

https://github.com/brainupdaters/drlm/blob/5bfdbced99dc2a576365930ed95f63921bf85190/usr/share/drlm/lib/backup-functions.sh#L19

##### DRLM Server information:

* DRLM version: Disaster Recovery Linux Manager 2.2.0-git / 2017-09-20

**Comment by didacog** [comment]
Closing stale issue
