### ISSUE TITLE
modnetwork server must modify /etc/drlm/client_local_template.cfg

### ISSUE THREAD

**Issue by krbu** [brainupdaters/drlm#77]
* Issue type: Bug
* Impact Urgent
* How often it happens Always
* Brief description of the issue:
When servername is changed it works for the database but not the servername is not modified on  /etc/drlm/client_local_template.cfg

drlm modnetwork -n <netname> -s <server> 

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): Disaster Recovery Linux Manager 2.2.0-git / 2017-09-20

**Comment by proura** [comment]
@krbu Do you mean the server ip that is in the file of each client instead of the name?

**Comment by krbu** [comment]
@proura I mean that when the server  is modified using drlm modnetwork the variable   SRV_NET_IP config file on /etc/drlm/clients/client.cfg is not modified, here an example:

[root@la-drlm-cont clients]# cat laraccontdb01.cfg
#
# ReaR Config File for DRLM centralized configuration.
#
# This file has been generated by instclient , It can be modified at your
# convenience, see http://relax-and-recover.org/ for more information.
#

# Minimal ReaR Client configuration
CLI_NAME=client
SRV_NET_IP=10.74.21.4

OUTPUT=PXE
OUTPUT_PREFIX=$OUTPUT
OUTPUT_PREFIX_PXE=$CLI_NAME/$OUTPUT
OUTPUT_URL=nfs://$SRV_NET_IP/var/lib/drlm/store/$CLI_NAME
BACKUP=NETFS
NETFS_PREFIX=BKP
BACKUP_URL=nfs://$SRV_NET_IP/var/lib/drlm/store/$CLI_NAME

SSH_ROOT_PASSWORD=drlm

**Comment by proura** [comment]
Ok, now the config file of each client afected is modified with the new server ip.

**Comment by proura** [comment]
Now, the configurations on DRLM server are updated with the new IP, but not the client side configurations like hosts file and /etc/rear/local.conf.

To modify these files, we need ROOT access, and it will ask for ROOT password for each client in the server every time that a server IP is changed. Is it the expected behavior?

**Comment by krbu** [comment]
No, we only have root access at install time, maybe we can add this stuff on the sudo config

**Comment by proura** [comment]
ok, sounds good! I will try to make it and test it.

**Comment by didacog** [comment]
Seems issue itself is solved. closing it
