### ISSUE TITLE
How to integrate DRLM backups with Netbackup

### ISSUE THREAD

**Issue by samurdhi** [brainupdaters/drlm#80]
I'm new to DRLM and realized that this really a good disaster recovery tool for physical servers. I'm going to introduce this tool to my Data Center. But before that I need to know that how can I integrate this with organization Netbackup solution.

Please advice.

**Comment by proura** [comment]
Hello @samurdhi ,

@didacog answered your question in the DRLM User Forum. This was the answer: 

> One of the easiest ways to send drlm backups to netbackup is to install netbackup agent in DRLM server and backup the ARCHDIR (/var/lib/drlm/arch) where the dr images are stored. Just plan the netbackup job while no DRLM backups are running and you'll be able to backup the dr images from drlm.
> If you are looking for something automated from de DRLM side is not implemented. 

Have you tried to do de backup of the ARCHDIR?

Regards,

**Comment by proura** [comment]
I will close this issue for lack of response.
