### ISSUE TITLE
-size 582c don't delete correctly the schedulled logs

### ISSUE THREAD

**Issue by proura** [brainupdaters/drlm#85]
* Issue type: Bug
* Impact: Low
* How often it happens: Always
* Brief description of the issue: -size 582c don't delete correctly the schedulled logs
* Work-around, if any: increment the size maybe can solve the issue.

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): DRLM 2.2.0

**Comment by didacog** [comment]
seems that setting it to "-700c" works well.

**Comment by proura** [comment]
solved at issue #67
