### ISSUE TITLE
DRLM build inside docker container (centos7) - drlm build system

### ISSUE THREAD

**Issue by didacog** [brainupdaters/drlm#88]
###### Quick response time is not guaranteed with free support, if you are using DRLM in a production environment and enterprise grade level support services are required, please see: http://www.brainupdaters.net/en/drlm-services.

Please fill in the following items before submitting a new issue:

##### Issue details:

* Issue type: **Bug**
* Impact: **Low**
* How often it happens: **Always** 
* Brief description of the issue: 
When building drlm rpm in docker container (for the build system) the drlm.spec file has errors with some %if statements 
* Work-around, if any:
No, just needed to adjust the spec to avoid errors:
lines 109 & 138: 
  change %if %(ps -p 1 -o comm=) == "systemd"
  for : %if "%(ps -p 1 -o comm=)" == "systemd"

Needs some testing, but my first tests have been successful and seems that the RPM package was installed correctly on centos7

**Comment by didacog** [comment]
I don't know why is working outside a container and fails inside it without " ... " but if is working on both with " ... " in the %if %endif it should be changed.

**Comment by proura** [comment]
There is no problem with " ... " outside a container, the rpm package builds and installs correctly. I will close this issue. I have pull the changes. and will be available in the rext release 2.3.0.
