### ISSUE TITLE
setting password for drlm user on clients:  could it be fully unattended?

### ISSUE THREAD

**Issue by jonicks** [brainupdaters/drlm#89]
* Issue type: Feature Request
* Brief description of the issue:
In order to make a fully unattended installation of the client, do you think it could be possible to avoid the step where we have to manually set the password for 'drlm' user before it is locked? Maybe we could previously copy its public id in the first interaction that takes place with the privileged user, or we could send it straight away in the same command using some of the available tools.

**Comment by NefixEstrada** [comment]
Fixed in #106
