### ISSUE TITLE
Error installing client on OpenSUSE Leap 15

### ISSUE THREAD

**Issue by RicardoJeronimo** [brainupdaters/drlm#91]
* Issue type: **Question**
* Impact: **Critical**
* How often it happens: **Always**
* Brief description of the issue: Running drlm instclient -c suse1 to configure my OpenSUSE Leap 15 client is giving the error "drlm:instclient: Missing Release or Distro!" and there's no documentation on how to manually configure a client. How can I configure it?

##### DRLM Server information:

* DRLM version (/usr/sbin/drlm -V): 2.2.1-git / 2018-10-03
* OS version (cat /etc/drlm/os.conf or lsb_release -a): CentOS 7.5.1804

**Comment by krbu** [comment]
Hi Ricardo,
Yes, at this moment  OpenSUSE Leap 15 has not been tested, at this moment you can edit the file /usr/share/drlm/client/inst/default/359_install_client_soft.sh
replacing the line 194 
     [11*-12*-13*-42*])
for
     [11*-12*-13*-14*-15*-42*])

please, open a pull request if this workaroud works fou you and we'll add the changes for the next hotfix.

**Comment by RicardoJeronimo** [comment]
Hi, krbu, thanks for the response.

It didn't work, however. Is there any way I can configure the client manually?

**Comment by krbu** [comment]
Yes but since we don't have tested OpenSUSE Leap 15 is gonna be a little tricky, can you pass me the content of this file /etc/SuSE-release ?

**Comment by RicardoJeronimo** [comment]
/etc/SuSE-release has been deprecated. Here is the content of /etc/os-release:

NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

**Comment by RicardoJeronimo** [comment]
Okay, I was finally able to install it by making the following changes:

In **/usr/share/drlm/lib/install-functions.sh**, I changed line 20 to:
`if [ -f /etc/SuSE-release ]; then cat /etc/SuSE-release|grep 'VERSION='| tr -d 'VERSION="';fi`

In **/usr/share/drlm/client/inst/default/359_install_client_soft.sh**, I changed line 148 to:
` [11*-12*-13*-15*-42*])`

And in my **OpenSUSE Leap 15 machine**, ran the following commands:
```
# cp /etc/os-release /etc/SuSE-release
# cp /usr/lib/os-release /usr/lib/SuSE-release
```

However, when I try to run **drlm runbackup -c suse1**, it gives me the error
`ERROR: drlm:runbackup:REMOTE:mkbackup:suse1: Problem running remote mkbackup! aborting ...`


What am I missing here?

**Comment by krbu** [comment]
Hi Ricardo,
please , uncompress this file on / and let me know if this works.
[drlm_update.tar.gz](https://github.com/brainupdaters/drlm/files/2562242/drlm_update.tar.gz)

**Comment by krbu** [comment]
> Okay, I was finally able to install it by making the following changes:
> 
> In **/usr/share/drlm/lib/install-functions.sh**, I changed line 20 to:
> `if [ -f /etc/SuSE-release ]; then cat /etc/SuSE-release|grep 'VERSION='| tr -d 'VERSION="';fi`
> 
> In **/usr/share/drlm/client/inst/default/359_install_client_soft.sh**, I changed line 148 to:
> ` [11*-12*-13*-15*-42*])`
> 
> And in my **OpenSUSE Leap 15 machine**, ran the following commands:
> 
> ```
> # cp /etc/os-release /etc/SuSE-release
> # cp /usr/lib/os-release /usr/lib/SuSE-release
> ```
> However, when I try to run **drlm runbackup -c suse1**, it gives me the error
> `ERROR: drlm:runbackup:REMOTE:mkbackup:suse1: Problem running remote mkbackup! aborting ...`
> 
> To solve this, I ran the following commands on my **OpenSUSE Leap 15 machine**:
> 
> ```
> # zypper remove rear
> # zypper install rear
> ```

Sorry, I messed the last message. It's ok as a workaround but if the modification I have done on the drlm_update.tar.gz is ok it will work for new systems as well.

**Comment by krbu** [comment]
can you upload the server and client logs to have a look?

**Comment by RicardoJeronimo** [comment]
Your modification works, it installed the client with no problems.

Here is the log when I try to run **drlm runbackup -c suse1**
[drlm-centos1-runbackup.20181108.104805.0613.log](https://github.com/brainupdaters/drlm/files/2562431/drlm-centos1-runbackup.20181108.104805.0613.log)

One thing I've noticed when I run the same command on my CentOS 7 machine, it displays "exporting centos2:/var/lib/drlm/store/centos2" until I press Ctrl+C and the only thing present in "/var/lib/drlm/store/centos2" is an empty lost+found folder. Is this normal?

**Comment by krbu** [comment]
Hi Ricardo,
no, is not normal, please run the backup with debugscript mode and verbose mode like this:

drlm -vD runbackup -c suse1

are you using btrfs ? 
can you run this commands on the client side?:
lsblk
df -h

**Comment by RicardoJeronimo** [comment]
Alright, here is the log file for drlm -vD runbackup -c centos2:
[drlm-centos1-runbackup.20181108.163345.3101.log](https://github.com/brainupdaters/drlm/files/2562650/drlm-centos1-runbackup.20181108.163345.3101.log)

Btrfs is installed only on my OpenSUSE machine.

Here is the output of those 2 commands on my CentOS 7 machine:
```
[root@centos2 ~]# lsblk
NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda               8:0    0   16G  0 disk
├─sda1            8:1    0    1G  0 part /boot
└─sda2            8:2    0   15G  0 part
  ├─centos-root 253:0    0 13.4G  0 lvm  /
  └─centos-swap 253:1    0  1.6G  0 lvm  [SWAP]
sr0              11:0    1 1024M  0 rom
[root@centos2 ~]# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root   14G  2.4G   12G  18% /
devtmpfs                 908M     0  908M   0% /dev
tmpfs                    920M     0  920M   0% /dev/shm
tmpfs                    920M  8.9M  911M   1% /run
tmpfs                    920M     0  920M   0% /sys/fs/cgroup
/dev/sda1               1014M  187M  828M  19% /boot
tmpfs                    184M     0  184M   0% /run/user/0
tmpfs                    184M     0  184M   0% /run/user/1000
```

**Comment by krbu** [comment]
Looks like rear is not well configured on the client side, can you pass me the file:
/etc/rear/local.conf (client)
/etc/drlm/clients/centos2.conf (drlm server)

**Comment by RicardoJeronimo** [comment]
Local.conf (client):
[local.conf.txt](https://github.com/brainupdaters/drlm/files/2562716/local.conf.txt)

centos2.cnf (server):
[centos2.cfg.txt](https://github.com/brainupdaters/drlm/files/2562719/centos2.cfg.txt)

**Comment by RicardoJeronimo** [comment]
Here is the output:

```
[root@centos2 ~]# curl -v https://centos1/clients/centos2/config
* About to connect() to centos1 port 443 (#0)
*   Trying 10.192.5.60...
* No route to host
*   Trying 10.192.5.60...
* No route to host
* Failed connect to centos1:443; No route to host
* Closing connection 0
curl: (7) Failed connect to centos1:443; No route to host
[root@centos2 ~]#
[root@centos2 ~]#
[root@centos2 ~]# curl -k https://centos1/clients/centos2/config
curl: (7) Failed connect to centos1:443; No route to host

```

**Comment by krbu** [comment]
That's the problem, you have no conection to the server, check your Lan and
ensure https is up on the server side.

**Comment by RicardoJeronimo** [comment]
That's weird. httpd is running on the server and its IP is 10.192.5.60 while the client is 10.192.5.59, there should be a connection.

The only thing I've noticed it's not okay is the time on the client, it's 7 minutes late relative to the server. Could that influence the behavior of the backup?

**Comment by RicardoJeronimo** [comment]
Okay, so I managed to get that curl going by opening port 443 on firewalld. Here's the output:

```
[root@centos2 ~]# curl -v https://centos1/clients/centos2/config
* About to connect() to centos1 port 443 (#0)
*   Trying 10.192.5.60...
* Connected to centos1 (10.192.5.60) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Server certificate:
*       subject: CN=centos1,O=SA,L=GI,ST=CAT,C=ES
*       start date: Nov 07 17:16:27 2018 GMT
*       expire date: Nov 06 17:16:27 2023 GMT
*       common name: centos1
*       issuer: CN=centos1,O=SA,L=GI,ST=CAT,C=ES
* NSS error -8172 (SEC_ERROR_UNTRUSTED_ISSUER)
* Peer's certificate issuer has been marked as not trusted by the user.
* Closing connection 0
curl: (60) Peer's certificate issuer has been marked as not trusted by the user.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

```

The process, however, still hangs at "exporting centos2:/var/lib/drlm/store/centos2". Here is a **df- h** on my server after I Ctrl+C:

```
Backup Id            Client Name     Backup Date          Backup Status
[root@centos1 ~]# df -h
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/centos-root     14G  2.1G   12G  16% /
devtmpfs                   908M     0  908M   0% /dev
tmpfs                      920M     0  920M   0% /dev/shm
tmpfs                      920M  8.9M  911M   1% /run
tmpfs                      920M     0  920M   0% /sys/fs/cgroup
/dev/mapper/vgdata-lvdata   10G   33M   10G   1% /backups
/dev/sda1                 1014M  187M  828M  19% /boot
tmpfs                      184M     0  184M   0% /run/user/0
/dev/loop110               2.3G  7.1M  2.3G   1% /var/lib/drlm/store/centos2
```

**Comment by didacog** [comment]
Hello @RicardoJeronimo 

try it with 

curl -v -k https://centos1/clients/centos2/config
and 
curl -v --capath /etc/rear/cert https://centos1/clients/centos2/config

if getting the config over https is wotking, then the problem could be that the loop mounted image is stuck after all errors.

restarting drlm-stord and nfs-server service and check if the mounted image still there in df -h or not.

Regards,
Didac

**Comment by didacog** [comment]
Hi @RicardoJeronimo,

Please attach de log files of:
<pre>
drlm -vD runbackup -c centos2
</pre>
and de corresponding client log file in /var/log/drlm/rerar/rear-centos2-mkbackup.timestamp.log

regards,
Didac

**Comment by RicardoJeronimo** [comment]
Here is the log file of `runbackup`:
[drlm-centos1-runbackup.20181109.153933.3376.log](https://github.com/brainupdaters/drlm/files/2566478/drlm-centos1-runbackup.20181109.153933.3376.log)

However, my **/var/log/drlm/rear/** directory is empty.

**Comment by didacog** [comment]
What rear version is installed on centos2?
On the other hand, attach the log in centos2:/var/log/rear/centos2.log.

regards,
Didac

**Comment by RicardoJeronimo** [comment]
```
[root@centos2 ~]# rear -V
Relax-and-Recover 2.00 / Git
```

Here is the log:
[rear-centos2.log](https://github.com/brainupdaters/drlm/files/2566592/rear-centos2.log)

**Comment by krbu** [comment]
Hi Ricardo,

from the log you've updated I see a problem with NFS

```
mount.nfs: No route to host
2018-11-09 16:08:15 ERROR: Mount command 'mount  -t nfs -o rw,noatime 10.192.5.60:/var/lib/drlm/store/centos2 /tmp/rear.dzpbmNVpE8fNiOW/outputfs' failed.

```
Can you disable Firewall on both servers?

**Comment by RicardoJeronimo** [comment]
Okay, I think it worked! Now the `runbackup` exits properly and a **df -h** shows 3 folders: BKP, lost+found and PXE.

However, I was able to disable the firewall on both servers because they are for testing. In a production environment, that won't be possible. What ports, aside from 443, does DRLM use?

**Comment by krbu** [comment]
Hi,
Yes , you have to allow NFS,DHCP,HTTPS,TFTP services to ensure DRLM works, let us know if all works ok with the rules you implement and we'll add this information on the documentation.

**Comment by RicardoJeronimo** [comment]
So far, everything is working. Thank you so much for your help, @krbu and @didacog!

These were the firewall rules I implemented in the server and both clients:
**NFS** requires ports 111 and 2049 via TCP and UDP
**DHCP** requires ports 67 and 68  via UDP
**HTTPS** requires port 443 via TCP
**TFTP** requires port 69 via UDP


These commands work in CentOS 7 and OpenSUSE Leap 15:
```
firewall-cmd --permanent --add-port=67-69/udp
firewall-cmd --permanent --add-port=111/tcp
firewall-cmd --permanent --add-port=111/udp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --permanent --add-port=2049/tcp
firewall-cmd --permanent --add-port=2049/udp
```

Then, `firewall-cmd --reload`

**Comment by krbu** [comment]
Awesome, thanks for your testing, I've seen you have reopened the issue, do you have any other question or we can close the issue?

**Comment by RicardoJeronimo** [comment]
No, it was my mistake.

Thank you again.
