### ISSUE TITLE
Problem with recover on OpenSUSE Leap 15 

### ISSUE THREAD

**Issue by RicardoJeronimo** [brainupdaters/drlm#93]
* Issue type: **Bug**
* Impact: **Critical**
* How often it happens:**Always**
* Brief description of the issue:
Hello!

I'm having some trouble recovering an OpenSUSE Leap 15 machine. First of all, when I execute **rear recover** in this machine, I always get prompted with:
```
[...]
Proceed with recovery (yes) otherwise manual disk layout configuration is enforced
(default 'yes' timeout 30 seconds)
```

After this, I get this error along with 6 options.
`The disk layout recreation script failed`

When I choose option 2 in order to view the log (/var/log/rear/rear-suse1.log), I can see some errors regarding rpc.idmapd:
![image](https://user-images.githubusercontent.com/4950815/49147612-10f5ec00-f2fd-11e8-9b68-6034d3cbe3f7.png)

This machine has a clean OpenSUSE Leap 15 installation. The only thing I installed was the DRLM client.

**Comment by proura** [comment]
Hello @RicardoJeronimo,

Actually DRLM is not ready for opensuse15, it has not been tested, but @krbu have started a new feature called opensuse15 [https://github.com/brainupdaters/drlm/tree/feature/opensuse15](url) to develop and test this.

**Comment by proura** [comment]
I have found this [ReaR issue](https://github.com/rear/rear/issues/1973#issuecomment-440247218) talking about that default btrfs structure which requiresspecial settings in /etc/rear/local.conf

**Comment by RicardoJeronimo** [comment]
Hey, @proura,

I read that issue and made some changes to /etc/rear/local.conf:
```
[...]
BACKUP_OPTIONS="nfsvers=4,nolock"
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" snapper chattr lsattr )
COPY_AS_IS=( "${COPY_AS_IS[@]}" /usr/lib/snapper/installation-helper /etc/snapper/config-templates/default )
BACKUP_PROG_INCLUDE=( /var/cache /var/lib/mailman /var/tmp /var/lib/pgsql /usr/local /opt /var/lib/libvirt/images /boot/grub2/i386-pc /var/opt /srv /boot/grub2/x86_64-efi /var/lib/mariadb /var/spool /var/lib/mysql /tmp /home /var/log /var/lib/named /var/lib/machines )
POST_RECOVERY_SCRIPT=( 'if snapper --no-dbus -r $TARGET_FS_ROOT get-config | grep -q "^QGROUP.*[0-9]/[0-9]" ; then snapper --no-dbus -r $TARGET_FS_ROOT set-config QGROUP= ; snapper --no-dbus -r $TARGET_FS_ROOT setup-quota && echo snapper setup-quota done || echo snapper setup-quota failed ; else echo snapper setup-quota not used ; fi' )
```

As per [https://github.com/rear/rear/blob/master/usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf](this file). The **rear recover** command is able to finish the process, however, it seems that /boot/grub2/i386-pc is not being copied correctly. After the reboot I enter straight into grub rescue with `error: file '/boot/grub2/i386-pc/normal.mod' not found.`

**Comment by jsmeix** [comment]
`error: file '/boot/grub2/i386-pc/normal.mod' not found`
is 
https://github.com/rear/rear/issues/1828
that is fixed by
https://github.com/rear/rear/pull/1843
on Fri Jun 29 2018 which was
after the ReaR 2.4 release that happened on Thu Jun 21 2018.

@RicardoJeronimo 
you need our current ReaR upstream GitHub master code, cf.
https://github.com/rear/rear/issues/1973#issuecomment-440227457

**Comment by proura** [comment]
Thank you very much @jsmeix!! I have tried with last ReaR master code and works perfectly.

@RicardoJeronimo you can try it with DRLM running this commands in you opensuse leap 15 client:

```
# zypper in net-tools-deprecated git-core
# git clone https://github.com/rear/rear.git
# cd rear
# make install
```

And putting this configuration in your **/etc/drlm/clients/your_open_suse_15_client.cfg** file of your DRLM server.

```
[...]
BACKUP_OPTIONS="nfsvers=4,nolock"
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" snapper chattr lsattr )
COPY_AS_IS=( "${COPY_AS_IS[@]}" /usr/lib/snapper/installation-helper /etc/snapper/config-templates/default )
BACKUP_PROG_INCLUDE=( /var/cache /var/lib/mailman /var/tmp /var/lib/pgsql /usr/local /opt /var/lib/libvirt/images /boot/grub2/i386-pc /var/opt /srv /boot/grub2/x86_64-efi /var/lib/mariadb /var/spool /var/lib/mysql /tmp /home /var/log /var/lib/named /var/lib/machines )
POST_RECOVERY_SCRIPT=( 'if snapper --no-dbus -r $TARGET_FS_ROOT get-config | grep -q "^QGROUP.*[0-9]/[0-9]" ; then snapper --no-dbus -r $TARGET_FS_ROOT set-config QGROUP= ; snapper --no-dbus -r $TARGET_FS_ROOT setup-quota && echo snapper setup-quota done || echo snapper setup-quota failed ; else echo snapper setup-quota not used ; fi' )
```
Now you can run **drlm runbackup -c opensuse15client**  and recover it.

**Comment by RicardoJeronimo** [comment]
Thank you both, I was able to restore the machine as expected! I had to run `zypper install asciitools xmlt ` as well in order to `make install`.

The network settings, however, seem to not have been backed up (or restored) correctly. After I boot, I am unable to bring the interface up and even Yast has trouble accessing the configuration, although it remains unchanged. Can you confirm this, @proura?
