### ISSUE TITLE
Add -C option to addclient

### ISSUE THREAD

**Issue by NefixEstrada** [brainupdaters/drlm#97]
###### Quick response time is not guaranteed with free support, if you are using DRLM in a production environment and enterprise grade level support services are required, please see: http://www.brainupdaters.net/en/drlm-services.

Please fill in the following items before submitting a new issue:

##### Issue details:

* Issue type (**Bug** / **Question** / **Feature Request** / **Others?**): Question
* Impact (**Low** / **High** / **Critical** / **Urgent**): Low
* How often it happens (**Always** / **Eventually**): Always
* Brief description of the issue: With version 2.3.0, the `-C` option was added for the client install workflow. It would make sense to add the option in the add client workflow also
* Work-around, if any: No

**Comment by proura** [comment]
@krbu do you thing that can bé usefull, have the -C (configure no install) option in the addclient like the -I (install client) option?

**Comment by proura** [comment]
@NefixEstrada I talked with @krbu and also thinks it will be usefull add -C option to addclient.

**Comment by NefixEstrada** [comment]
It's not working because it tries to restart the rpcbind service which isn't installed. Any clues?

**Comment by krbu** [comment]
The point of the -C option is to allow only the configuration without installing any package (user must asume the packages are installed) , this is usefull when DRLM is configured on an environment without access to the internet or any local repositories. Addclient also can be ejecutado for  a new server tha is not up.  Maybe we can go on and just advertise on the requisites on the documentation and help.

**Comment by NefixEstrada** [comment]
#107
